table Dim_Shift
	lineageTag: 837f0e7a-0482-54a9-85e8-4f3b738137b2

	column ShiftID
		dataType: string
		isHidden
		lineageTag: bc5dfecc-fffe-5079-9c69-35adc97c6a5a
		summarizeBy: none
		sourceColumn: ShiftID

		annotation SummarizationSetBy = Automatic

	column ShiftName
		dataType: string
		lineageTag: cae3c1fa-fb8a-5de6-ba6d-366260117d91
		summarizeBy: none
		sourceColumn: ShiftName

		annotation SummarizationSetBy = Automatic

	column Hours
		dataType: string
		lineageTag: 6e69c1ce-9312-56b4-8710-dd9f48aac490
		summarizeBy: none
		sourceColumn: Hours

		annotation SummarizationSetBy = Automatic

	column PerformanceFactor
		dataType: double
		formatString: 0.00
		lineageTag: 16e467e2-7e32-585e-8531-ef6c86a8a084
		summarizeBy: none
		sourceColumn: PerformanceFactor

		annotation SummarizationSetBy = Automatic

	partition Dim_Shift = m
		mode: import
		source =
				let
					Source = Csv.Document(Binary.Decompress(Binary.FromText(Text.Combine({
							"HYtBCoAgFAX3nuUZv6Ki1ha1kaATSFi5SMEs6Palmzcww1sOs4VJYImU6tQY3e0vzNpvzp/KrnpQa3CeCQj1gpqOiOfVv8gzYj36R1tjdyTHizIWytqaSUizHwFJ8XSMgX0="
						}), BinaryEncoding.Base64), Compression.Deflate), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"ShiftID", type text},{"ShiftName", type text},{"Hours", type text},{"PerformanceFactor", type number}}, "en-US")
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

