table Dim_Machine
	lineageTag: 63d5d601-e4a0-5ad6-8cc9-310928c17178

	column MachineID
		dataType: string
		isHidden
		lineageTag: 04e579c1-55a0-5b45-844d-8846730d669e
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 35be8e93-5ea1-59f0-84e4-6de38d80a2e4
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: f552c5b4-ca45-5274-b746-a88a6943788f
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column InstallDate
		dataType: dateTime
		formatString: dd.MM.yyyy
		lineageTag: 34303bb6-b845-506b-ab1d-8109631ee9fe
		summarizeBy: none
		sourceColumn: InstallDate

		variation Variation
			isDefault
			relationship: 97949f2d-0f04-4ee4-bb57-c4a008f28014
			defaultHierarchy: LocalDateTable_4d0e342f-6e29-45aa-b89f-3ffd04123fa0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Line
		dataType: string
		lineageTag: 43299b57-7ccf-5fa7-b79c-c06ba15c9598
		summarizeBy: none
		sourceColumn: Line

		annotation SummarizationSetBy = Automatic

	partition Dim_Machine = m
		mode: import
		source =
				let
					Source = Csv.Document(Binary.Decompress(Binary.FromText(Text.Combine({
							"dc+9CsJADAfw3afoAySQ5KrWUdpF6Dmo4HxqwML5ge3i25sSEESdLlx+JP/EdDx3V101EL1ap4tC+/G1e94VVtd+SDk3adBJJIZ6XaM9rZdF7HIGIWGkgDw1Ik7kiwjSDJmMBCfBiHwQQmaUkZROyjdp03BWM7xAqpDGTVPYt42HCbC5HW5Ddyz2mk/6GIcFayFXBmcO5Q+07AtkMTiH5Tb6xBKWfa+XQ34Wtb4PEBQ2V7mT344sHgaavAA="
						}), BinaryEncoding.Base64), Compression.Deflate), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"MachineID", type text},{"MachineName", type text},{"MachineType", type text},{"InstallDate", type date},{"LineID", type text}}, "en-US"),
					#"Merged Queries" = Table.NestedJoin(#"Changed Type", {"LineID"}, Dim_Line, {"LineID"}, "LineTbl", JoinKind.LeftOuter),
					#"Expanded LineTbl" = Table.ExpandTableColumn(#"Merged Queries", "LineTbl", {"LineName"}, {"Line"}),
					#"Removed LineID" = Table.RemoveColumns(#"Expanded LineTbl", {"LineID"})
				in
					#"Removed LineID"

	annotation PBI_ResultType = Table

