table Dim_Line
	lineageTag: f1832a42-285a-560e-bbeb-e62f162db2af

	column LineID
		dataType: string
		isHidden
		lineageTag: dc369773-a66e-51f9-9db8-f886ca39f0f3
		summarizeBy: none
		sourceColumn: LineID

		annotation SummarizationSetBy = Automatic

	column LineName
		dataType: string
		lineageTag: 8fdf9353-41a3-5b33-940c-2cb7c98babc7
		summarizeBy: none
		sourceColumn: LineName

		annotation SummarizationSetBy = Automatic

	column ProcessType
		dataType: string
		lineageTag: 38e3ce91-d84d-55c2-b4fa-31b55f9b56eb
		summarizeBy: none
		sourceColumn: ProcessType

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: 997e59d0-22a9-5a5e-8b67-777bc9ea45a5
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	partition Dim_Line = m
		mode: import
		source =
				let
					Source = Csv.Document(Binary.Decompress(Binary.FromText(Text.Combine({
							"88nMS/V00fEBUn6Juak6AUX5yanFxSGVBUB2TmJeCZePgSFYWsFQx9nPWUFfwTcxOSMzLzMvXcc3v7gYKG8EkTfCJW8MkTfWcUtMKspMTizJzM9TUFMIT81JQVJlAlFlouNYXJyam5RTCZEAAA=="
						}), BinaryEncoding.Base64), Compression.Deflate), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"LineID", type text},{"LineName", type text},{"ProcessType", type text},{"Plant", type text}}, "en-US")
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

