table Fact_Downtime
	lineageTag: 36228163-f86f-53c2-ae49-3ab142950601

	column DowntimeID
		dataType: string
		isHidden
		lineageTag: 741b9682-b471-59c3-931a-273d3d19106f
		summarizeBy: none
		sourceColumn: DowntimeID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: dd.MM.yyyy
		lineageTag: 3d55f7d0-8201-5961-aaa7-7c78cf7c1635
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LineID
		dataType: string
		isHidden
		lineageTag: 87af352b-59d2-516a-bd5d-04f258ea478b
		summarizeBy: none
		sourceColumn: LineID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		isHidden
		lineageTag: 5dd8a089-fa74-58af-a5dd-e53cc4ae5ce7
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column ShiftID
		dataType: string
		isHidden
		lineageTag: a0f9a6a0-9064-54dd-83a5-a8cda6279b2d
		summarizeBy: none
		sourceColumn: ShiftID

		annotation SummarizationSetBy = Automatic

	column DowntimeReason
		dataType: string
		lineageTag: a21dd066-befe-5c5c-9598-4220c92f1f01
		summarizeBy: none
		sourceColumn: DowntimeReason

		annotation SummarizationSetBy = Automatic

	column DowntimeHours
		dataType: double
		formatString: 0.00
		lineageTag: ae73e700-33d7-5cd3-b98d-19fed42f0e9e
		summarizeBy: none
		sourceColumn: DowntimeHours

		annotation SummarizationSetBy = Automatic

	column DowntimeType
		dataType: string
		lineageTag: f5099a0c-10f6-5634-9c58-2c9b1867f35b
		summarizeBy: none
		sourceColumn: DowntimeType

		annotation SummarizationSetBy = Automatic

	partition Fact_Downtime = m
		mode: import
		source =
				let
					Source = Csv.Document(Binary.Decompress(Binary.FromText(Text.Combine({
							"lZ3trh65bYD/5yr2ApwDiZRI6Xd9gBZITvqRG3ASd9foxi52nRS9+76uDylyRGpOFljAhvm8MxIpiqIozfsv//P566e/fvyX9+/ef/j68d3vPn3+9ufff/jzT9//9B8/ffrPr9/+9VXw3z9++PXLZ/3rP3/52y+//ub9H8u3/+o7KEC/LfW3Bd797vHX3z/+f//un3768PnHj1/+/vGXd/WpsUiDl4aHdLtKV5VGL90e0uPdy7s/fP3pIdieuIpgiwX/7W8ffv709X9/+PTrr3/7+O2XuwB9Ad28x2sX/PCnXz5++K+/PJr7rjzxFIgi6Nm+fHkilWYvjQ9p8k0tT6OJ9PDS31rAD+k/fvny86fPP762AJ6ABJgLoNd+h0eT//XnD58/f/zLD3/98Onz14+fP3z+8zes4CtWi8fit5JuqvVWuj4VUVcFL/1dC65/8KmIzqpRLr/2Jj5+O2rA45WGYG3HWtLu8jRFG7V77FtL+uPdvIXAE2tHGWUP07+/fwyYXz59+PmHX3/68svXDz9+g5o+hT0kbXL9RaLzOry09G7UlPrE2gMzxnbbfehG3gxKBL2EkLwfVM+ITfrWiK0A7NLftP+H//74y4evX3754cPfP3z6+cOfPn3r73f9qYglgzGEaTrtqpomHQDNA991+eJtGEWR0L309/d6v/kG1GYvzdfl0V5C36DDEdhD3xtxta+He5DBAsMD3xvxfgf0CTMCLqOL4VUal74fAy3so4e06A6rl5Y+MtKw3DLCrfSjO1UaY2nv2fpTl4Zii4CLm1Vt4VLvwzUspxwZNonvQdohTJzIYxCJ4SF7TAaRb7hKDy/9ffjED+lPTTU3Y8w1v0lntRJLR8ba5c2aUbed/eKhavqtgQelA65jaYrym1H+mqWeAy9azes1D31/ynPYce2piotrxhKmjtv4Waj9RzuUufmq3cAeij3WY9LSpwwPxLOu/vyMpJ+9mbF0cS+x9PVlQPqpVw/I+IqNX7u3L90/JhPpqd1Na9d29IAM/Mg0UdreWwxlpgnaDUv7j3lrxaG7Is1A6LRD37SfPU09QecY3NuGBhoeCudTFsfW5600PnXxGlQi6X1kyrvQMgIA4wEj5ahrIvDQijz2wVIUwgjKfG2TaZuaxwI3aEICMtrHm1mgCEM7g+HQN2ZGHEPutWTIkFE4Zaud1VEzlt7bQCscZqN3PgYrxulx9VDwXo/QWQyRIZaOI26NQBh3DEOVPDpMhj+36Fkvl2DB6IO7B+Iwqi3fzbQDpGtKY4DMsWDUszpo2Wh8mDlomxkUmB4Q7x3G5dK1wyh9mkY711BVukbS8SN0xhqwQ1uoo09YqkY7NSRLOWn7aB4LVkvwRPqQHknHzdDAdlAEvWzLavWjgz1w0rouLsfwkLjqbQWjLZ8xsD9lqLuaJWJekqhIlz9TtA8rPwNhtz1CBOm2CR6SYegcxJJGL30KKCzWFoYuXgumIOm52T0kNhN5FTWdSTvUtrhdtDnZS8ssd7UZXVvPEQEuXuu6qJ7zVvjhrb4L11J24X5wh7VUD4hhiXfrKgixoM9lkUgbDTcTXG1doi/ePJDPx+0JQKC+Q5jlKPRJ5KGb8EJbxB6TjGFkR11f0Ci6Gz/ndDdFeMbC8fJPmlNLTN3Fv7VWD54cl8T0tRoroONoWqm0WtFDYsFXY5Bka61tB/ohypaZq9Yeg9egVh9kbGGaztsjOtQEQq0cQVkilYZgw2PBHLyWdLXOSDqZVqQ5UDwkfjVUqbwXLDuo5ehV18qkAuwQ3A8iQI9JZOgtoWj+oELzQB6KFI3tK/QdojBObzpPVCAPrb4LEg9i2cAx5NNgYp0wdmlOOw30IcsUar2ZkJuYAhYP5Tlf0DCxYvXQ6QWLJhQqGmMAY0Hh5F8RvfQKy/Z192pO81ActcOyauwxEKlzPYUiKMtIryVrRfbgCs+CpylkzAHNHJk9TXYaKk4PrrbtBiE7M7WVGNp6UIZeqzuwp4na8gkN3gKsRFRtGAHZeJBwq7YWY99DlofzkH5q3Que3KHaQKO3Q0VbwjvE13iRxQs2o3ib44wV/5hItUHTg+EyXDJjtZdIOmmJNL/XGPreufCEKgheMHcwuiKpHT2zYqggdyrq7i2GIitBXY/WbpTPx/QemtZTDCXrUn0WR9hLqtAuCu3jHwGNCfXpwXxtazwvFQ+FaWLJrFSqkfRL6Kdlx7sSeChe2JYVshBGQDLtKmRMYphuS0xCX657bA2IvUUavBJ5KI8LYPkDMgYxj5k50MxcpRFDaW5ZNTV3EJNhpV6Ui4fC9RzIu/EyBijx7uDjt0UYvHCerHiEoQphBD2rV9c1FbdI8Brjk26rVV5qB7yJn9SQmSIorZYQy2T22FofBYGAMGNn2sF7qAvm6cEVHAcjVLpvlB2ys6f6plFjQV95I/01jM7bzW6KDv6BHhIvdi5JqaN5LN/CNBPbMFbQD4lWVoB2ALKniK0N9pCM4W1vTZ8yIuA5nKakFKCOuUNZ3gOk12bxUO7PV/lVNclAyPdvVxlBNYlAsPHDdXRK+00q0MnHM662pXlKglm/jkQtEagmCwh0XE73ZZ4mC3gDwZpkTDIQ6Jgnqk9De228FTLRoEkMwjmaWmU9YBKEZpMlbpMMODBJQuC4kuThCppIw620hoRgEoXAN901SSBRP65sc7ZTtFrePRRuqYNKk5c+qrEKxAtCO4O/lh8W7aIRC7r9GBDh6YXjldtjpMuva0rQAfGEJzEsaDoQbQL24u67SsOS7mZOvSZymr4TemCNpX1+UCXU5iHZ208KD0QNtUfYteySRZoi6WTtBpVj6XCeU8iom9IEyRDpuUtD4gz0vaB4KM+qdJ2tAKqHwhhQlusAEEnHabWq72X0PrOmi5FA88ISA15nTwliAZamL7nLYPUg3gzIQ6cdIdZXYw8F2dv+BGKBMCLpOKc6VRszghK9y3th8VC24JKH4FL5/6f4TnvzK+cNCB47hZpNn4U7RMFe",
							"qqTRAJsHRP9xMCCFpIDGCuCmMLhpbANIEZZn+1afcwTGA0GnHxweWsVNeYAMaEwCXbFG0O2vTCueiWOjVT0HrXpATCipbZRh1CDGsipcaMYc6K7gSlvTPBTMlLAm4NYj6ecwzJMQHBp56JjoUIg9lNeqrUw+tLFD2cJFp4NmbIBvpgN9Ui8eOqVWu5awQK8xdtWpTp7dGMEwcYCfQfTncZfOCqWl9gh681BcQyv20ruXzofZ2nyGThEUB0zaFt6ZrepWzaUbzZ9LTR9PEHfY5w5Buh0jxQtAxWOnVbWWGQBVT53qikQ1BJ7RnE3mQfUVcQdHmvmX3UCgZQqmojSeVmXfFah76LQTpG6HaIdin4B6gAeIPZTHhn0pmZZluERTWI+trzc9lIcwVfcDgMsOtZvKZeD6VmiVWACDh+KCmFX1DYwRkIQX0nPcdmjf7C+6NAfuHjiba3sa+nrGGpqxu3ggaoDB7LFTMlB9EQ8P3dSyizviGWNhLbu84CgxdC1thFG9YHCAY6XMYcCt9ErMwTC6vy9gQd3eg9F2sGbluOKyRvfQsZIVBnnpPOxFA/EO0SmfK55qDA+Gu4hNW2I0bnNgSbmQdPcsHgsfIhVWMGssnVYXKWhswG+/7a5azHGiZ4Ljkmv3GGbz0rlfN3HR7BEU+3V1NJNiKLNQjXjnsgQsN52gk9wcHjo5gLVvDXPuWE+DBfFRWJY5YD0cQ5NUJZa6A83sH4i3xQJe8KQfcTSo6cD221LjeHIlelDzgK/SgcGAejvUBOBF+pqzkpwKag7wFZBpbDskrH3DHohPxenbj0j6xRcHgr7MXNL29Oudm0TNBjZ/kDVyk+LCUbOBDrp6CelZzQa+Ssd5mzXJYTVqHmmAsE6tYW0ekAj9uq3QtAFG2fM49Fb9E1aKoLUHKUtGrBwLJolJ/f3hsfPBiKHdO2PMn2wRfUPx0sEu/9pEQFiKriU+jb+SGAjgpU8lJdqrgDuEWW04Qoul4wRVEarH1OnIAgJ56HSces0hCLxjPYmjJcmCMDwUZ0vWCVuEGQOxiUnGCHFpv2JccWwcKFYvrU7ldcNCEq2IsAseDtHr76PH8mUUacIDsXno1PJ1NA+x79hIX1HSC4jGCNpNNlgGDbJnwg0GfS+j+W5G2DWnIvEj4oyAYEqWXm7FA/FCiFcPt+qBLM+uHqgZ9VPahhWcYUMPnD1dV6x5LLeXrmcNsPUYSvKXQhm9c1qKXFc809gD4dUWsgeHbcTSUken47xNL5gXQJnYqi+Ng93CuM6fGj30ugPbTSTr58FLS8iw3S0i8hjJZxpQbfelbXcmNnEqMvr60jfATX5rlZJjpx3LXZjOR509psG/KFK7eCSCSYBW9QnTg3HU+CpMRvMYz9erGgOpRtLXTV2VBi8tPeRHedctACSMgS2illFBzQOnDV0TiFOPsVO6C4ki6LKUkFoqJN6lt3Su1P0jjTdIqwmRUXCLjy2uo1PIZZduaZYKteQducZg/FIMkfRLnNJBRi99Uhyoj+W2U7zd76NvZLR83ugw7pPJQ3mlZTNt5x3CtLhvaAcPj50CPw2x2Ch/HI8YGRc3yg7V7CCPDN9RPXSXd9J2DfBgoKZ1YhkHRtIvxwJ5HMYS5nHvD8yTegzFBj0olk7iP30z3jFIsojKDM+EhdQ6945lAViyZujCdZY3SA8xlFkj6Utdri7fJnjp00a5mRcmeixs7pIWVXd7KDPON+gcqHm5bk9XxlG4alzzchdoK+kUTWg+zgAc7Biwdu9YQM/SUbKLgZqCc9KxA5MNy6YJuO7vcUvPOrKANQIvyS+Zqptm4y7Sh8Lkpsm4bsuW4q0pKcZopXnoXMXedCu5le7Ba6BV9bXIC55XxlKJ1ArHmE+36UPGLp0d9y3CzJhJJsnXUdlqiTGvSBBpo3a+vTpBLjxsFTx2SpBIRVKrmEFBZYQwRv/jUBlI2vzugdORYvF7rVIEPd+euGmVYzAcB9oP463Qukau1ekhWUTFG3mqXygxFsYL0ulQI+hwLZEMClhmUdMMutg3oBdOL8aTLoAWAek9D9LdsCzCFWa5sLFp2ymSvkbuMg6AvXR+bG0VYjQYEfR8c4Vkg+mxcB9U/TmWXZqzI13SVVgjaJ/RZOXS0Cgcs4IdmWEbope+uXJTOhlbhD0fi2Qb9hjadlv0KRQBd+mDhhxj2z2Kon0cHjgWjjecXjreqVihT2slBrL1niqnGd33rLRWm93AS4c3jYotNtyFW3ZbmT6heSi7MbVoA7oH4osejR9utAOcb40KZRR+XoFVrdBvbUTQ+axgazOGstM/rZcY8EVk8k693kqvEqbWwUufbisjhYzi56EFElK33jxwvPin9e6lT7daLGhpHe7vmpCcdevssdP+89RnjRjyqy/xDH3u0nuB8zqB2qjEgJtuZSXVqHrp8Po/jW8JIul1clsjdFo6NhcfXq9LVenmpUO/AfrKfZdu2TEPfQS9HWKF2ENau5SEPKg6GB7MK0RXCUijGUF7VKuugI2m4Sbtox3BNYKSvQBxigweyuZNObvTGD3wtm3Pxi3G4mmQeyQdrx1XU4wh0Mn7aIexB0Lj1PHEw0sf30miDJ4eOh5mFjc6jPb55sixZKLaqG+FQLPFbcDbnySHm9tADx3LR/X1mofCOwQ19B99l6bsBIy+F3koSGnoVWdtGN2Pm4XwOmfexoiwxAhUn9NDK8t8GM3TGMG8iTsWVD10TtGpf5oQYc+Jl54YSV/u+pbDTM0k9Nx1kLGn1aOdTXN6ZGu59vBOA0jN510AH9Dqa/EuXQOXrJk2TeZdgKxaXRcamtejVTiGWU1F14Qe2TKzfC3ehKuey+OVNfy7pvXIlqglG3xdE3oX6euVPuJfuybzyN4FeTn1JivxXnokHVfLgkIUQ95yh0izlz7WEvUyvPTbZrpe5o71YEaVbq0lkk8OYku7a/XQKeMt2ateYYeyHAErhNGT4vBKrljp1WgenfPKL5jptXvolC+U",
							"ffleKYOC/SQZLJU9dDowwPqk4aFzOkpmpV7njuW3okmY3cFYRUvd3zrU0aHGQGzbALt0DfbeF4AeOM1h6gCg7RBuFbYi3GPhbPnbwai+38yQcp6nA+/QKtLsuu/WYXhBvRleTuOL3Nzlsgoc0RWWmEnqm6SH0Kj4bl+3KQQekgGS5brVjyF68HRCYHkzbJ7K10fGm6FR/V45u3I+HckLhkUKrC3gSHq/zlZnOBweyE4eybdxOs4dyDPnTcOP3ooHT/fEST1Ob0v/tRy9Kiy/0MBDpytS0GDosSBeX9uQvbVdmowCRX+tR3LJdrlYRyMPBYkMrXDqjXfhkW226Osvvdea3Qw+VA3TS5/jAsne9F4i7CWsNdGR0auHgjWNmXa70TVkcXzX38ZYOjw7qFDzUHyqwcwBvXvgeBWKQkbldi98S4OLl+vsgdOFpXKOoPcRQ/GOq8acfUbYZVaTnGin4qVPnyWR2vJORu32Eg9/Bk6lwUvHeUGVRi99Cuh02iSj9vOBLDNBU4+ha4JTdso60Q5A6qtE98SeOm5O67uNGEqmYKFm9qggxSYQFw/lF66uG2g71x3almYSgzB44bgES+yXjQGcPhqBCjQP5Akf1ERp5+6hN66e2JjAPGak1lGMzrxDdfuGlepjeOn00Jq+0/TA6cZcDT5GiaC4VED2aPqoHsovyTELk7G0b/K+yUlWsa+BMRR+DKOP5qVPuU9V5egeig/yatMpko6nx6oQx5AvEdUXWoq/XOWYF2L0MXeo5pcNSI/N4rHTwRA5p9ZnjaDLmT515BO89LluXopf+kSPxZ/+NJPxbDHgvwyl0kbr7Vj2tSrNu8ndmaPk749Vod2k8CApr0MjPbz06eo6je9N7g76TenGirnJJPGg32T9xWLIZPCg31zIhwoZG6DsK40qjJFw/ATZCCWTxIOk8K3rgCSTxLvsd+THdskk8Vyq+1zXTyabd5shL8KMnalZYV4VaHrodByparEQmcSey6qHRi19YRJ7NxAaCDyUu2fSND6ZxJ779FD2IT/SpB7bDHj6AQIxIE3rsc1on7eLSNN6GxTMadrhvEOYXLYsEyFpWo9t4jyLOWVZQ5rWc9h+tamODE3o8TqvzcknauT0NWlSj9MPIy1vRZrUY58UPt/4Q5rau2BZ4o3AGALe1MqvoliCHmFBbZMC5IH8BpRVokbAHsr7eX0gi2BE0LqWYGpfzUQwyaapbrD8I+D6rCuhMYH76/5B53lC8OCp91gh9NC5VlGCXcLmsbhsbZ0IJuwR8HI8okJo7OHuLjPJ7RByDKX5T7FyHB7M6lWnPmlGwPEeMGolYl6O62pqxiTyBRzq4WZq4IG4/mRFytQwBjaXIP66GQOYWRxCKt29dBC2d91BoUaxdFjZoE1ear/Jla5qJWrDQ+cbxXWItumx8KCaRC19adwVxUanv6nXSPjgNWSodPBgvith+qxjDKUTQV9ary0+baQ7A9S7F/bfBllb89QpFownvc5e+vSRWLlvnvrYoe1z5V1VNr10cF6zLV9IRsGnA/hy1JSoeuDuJlFZmhJBBF6iA+l+Msqlu+9AKdR2qN6eeibqMXZ1UBqLEnng5h53UQzxjt3d20E0PJRnc5p5QWMCHGfWzWTPywSg3JxXlA1H4hpBceCipsngobeUFhFjBD3fQC2CsuhfzpYQ9xgLc4fS20weOt9GpRMws8duduhlGPEyCKjplbd9BbI8PXByrroaHMYm4GY1KFlgGtVDwbS6bkmnAZH03UUKNDDGwqS2dNpoMRTWc9IwVoBxttH+Nnnp0ykbyerS4Bi6nh8AfcqIgOvWmgjPXTj8NKS0eJa3AKtMjKZRta3fkNsUJX1PE7xgsDOwdpJoopc+fVtOA5rZIujl/FkNmkbJfPtFulUkS5MiME1kKsYxFsaFCg0Pnc4Lqu+bM4bSVd+rI+NSPHjKa0opPpe6Q/2mxpSLsYpxs3WmX4zngjHl7wOpIt0i6Zd0RcSlx0D45Q8uxgzOZ+lX7pALe+h8L4tkqbkMjx0TzvqCM4ISn8d16f4Nx+WHUDWi0i1Q6YYKMRZNsxLUcEUPHT9aKkZgsoBY7y4Ul+42OUCst/EdaRdSjJ2KzthkAbFmX7zWJ4xdeJvG1GpM0s9J6xJGhrAm+8a1/jGPEFiTfePw2XCZvliTfcPWMN7cW8Wa67tQ0RVZslfOmu8btvIxmFq1+X0BLbs4SJtNsXBousKwZ06bOU0fNDwURwhNkxqsyT4DdHvBsbwOFi8oGYqtVl1+GWsMnL4Oxmg03m9c/LrplxE9lm9Ery0PxrZDFLRIUieM3QOne130IUbzdPe5OxmxyBF0n89jHB48HY1XJ44zhs7Vu9yKx24uIZQOacYs+ObKDEnucQMPneo0NaDlhjtFN1Xn3JqHciWjrkq4Lcuo58XwclONIuZ5H1DaCeyB0+30XZszPJQvfMZ6s+mZk2ZJc1rcl0HUep9IkWb16rHTl0B18ukQQc9x8Rh39NLhmVWpZuPedun83CTpUO/dczcrCrHSTjHmp2fRZzdGAGl8ugqbuA8P+AtMzcDsMxZ0CWt9ayqxdByLy2KfqcZYeORY3ozAQ6evtUnoQBgz56oGJqN7vDvLy9Qj6eB73vpW9DZAHTqxB057VeswLtPwWHCzH+gOLJPRfDumTZuu5ZmLh+L7MsUKue7SmEdy0g4Gj+VnJM18xhhDWyfrU5oHztclSQaU2Wif7y4KYSYvfSwREHNkjqDnYy0m8/DQaXe4ah8YGxg3PS3H2XgUD8UXSIqZjRpJn7/JysNYwO0RUWnMwBjaIjsxmdGypwRzkOh/9AhK+lm7jCIojuplqA32TLAHUvWIOI/hpfPcPy7HNGYEJcvkV2YWz4QVuTrNz6V9sJuV1wWWbHzwBA8ErliPOvPEWDgpcxe9zxZhz+kX2nh2D8QFRUYbkzxwKo3XOXsuhZv7J4LFqALDA+GGa9dWTy+dbyeiTvijlAiK42JJ841SPXQ6",
							"AiRDfhSj+Ha4Hw301dAD522boS/XPHZeVEil9Cg9xqKOGMKQZ05lE6tZxgrsWlgiN5klRhle8HRZAWjrZwSl0aoopxaPBXdcrMKzUY3+6W7S00eAh8JoXYbwqOilz1/AlTTXqC3CLhHSeojROb+hQEnSqaNSBJ4ziaOyh07OWM65jzoi6OU4gY86Y2i76Ut0Y5J+cHsXu1iBSfrdQyAQRND5epRhUn8wDuV3U4G2A3f5+GFSf+6ui+0aryoAeeCUiRfVmPQfjCAxp4o3KT93qXGy0hGTNok/h21eVgCTAISR7Qzoz5vsn7kD+XowQnrUpP2yfHbVbMsw2T6sN6Xnsk01NNs3/d0WR3vSjN98y00VqzpiaNpv+u8cXQeWrHGHpvzm9WaIwIdrm0YM3eUJh6b8LuA5VTM05TdtqW72aWSptBua8pu2+DZZKA3N9U17g0M2m0tgPTTZN+12RHK1hjaoeeh8XR7os/qO5dfYLswYRbs5AwBLy409FnzcaN0AONqIpK93HuorTS8dDlPZlh+9RNJZd0n6bfQaY+Fl4KNDLJ2dvh3daJ5vv3ahdtabx04HCuT0/OjdQ/GFjMYPdoqAeJG4+pljKP0+or7e2ME9l6g9bZQ/jtkFkl2pQcUz4YG3ptL1Vrpp8m2Q0fy83fZYS8VB6MH4ayxGK9R2INr60dmDegxEuXcp1xlEHjodFFILI96h/CNNOifS0nwtd19zE2buDCSfelQlcfFQvnhcn7sdXCMoDuY0NuNlDrUeX2/d0jAYPZS/ngltuGVQ8HoSs3CPoWTuUIw8dtwWFUviZRS13WSzV1pr8PBYtmcr2yqDjUWcPxi7Ll0do3goKOBbeaAxaiwd9rU+AiLoJfxqvWzpj4EeOn0TR5cdw5gCxeXe63OIY3QvHa8EVhnYGBQDidEoxju2leZqnDGGlz7f+aDT9Jgx5m8IETueZZdOP/UiepzVQ1mVhaSlx4QdyK7zUscxMXpKnGMd+mothnz1syhkGsVzWuypL0ReOp9oTepgsofO25AmCJjDg/FJmPXdtjFnBCSpg9fXm8Xof9zu9so6Z5bqsfi7bKh1mrOAByQbtH0cUJ+AERD7MFSoeUi/MfK62pbygFn6Ljiy3dpZluKhHjIFQ9+DI+DluKcwy8ig/BrNWWYMJVGzPKsWjx17FwSqHjqlP6W+ZNaleL29YSuwmvpeGEtvW7Fiv7V5IC+vWpXGs3YPBanJqhHCrBRJJ1+cV4gjKFtb6nCsI8ZOZxBmnR6KP7mqG1ETyi4/srslJxit480JEX0CvJXRrf4J6JmTd5VzYBPaDm17akVfq3vpm8Ma0r9gDKAdqx1Qp+EJ7KHsm9oSHE0YMRBWVCk0Y8ifDhNpLJH0HkjKIn5i9UB+RV5fNoxG+f3mGvv1NdiJ6LFz4a2ap0kI3mJVM+DTpASh31yUI0mZadKB5t6L4Doe7T9jBLd3MIsPNOlAB233/Yr89PK5ea6b4abJAcJIQ1FpuEn9wbi5rkCnfJMBhHFzdan2mMn/ZZ/oW3VI0yT+3B0Z529HT5P4c5X40TpEjmNMk/Zzt0Ofb4maJu0H8+6CFVGpyf5hib9csE5hTJP9y76Ntz7DMk32D8vdmQ2Fagx9D6xQ64mmSfuZQv38GHD/zf8B"
						}), BinaryEncoding.Base64), Compression.Deflate), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"DowntimeID", type text},{"Date", type date},{"LineID", type text},{"MachineID", type text},{"ShiftID", type text},{"DowntimeReason", type text},{"DowntimeHours", type number}}, "en-US"),
					#"Added DowntimeType" = Table.AddColumn(#"Changed Type","DowntimeType", each if List.Contains({"Planned maintenance","Changeover"}, [DowntimeReason]) then "Planned" else "Unplanned", type text)
				in
					#"Added DowntimeType"

	annotation PBI_ResultType = Table

