table Fact_Production
	lineageTag: a3002378-1315-55a4-9288-598ea18e2409

	column Date
		dataType: dateTime
		isHidden
		formatString: dd.MM.yyyy
		lineageTag: 66707ea4-5338-58cf-b242-bfaea03dbb33
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LineID
		dataType: string
		isHidden
		lineageTag: 88f31772-7b19-542d-bbb5-7603312e2297
		summarizeBy: none
		sourceColumn: LineID

		annotation SummarizationSetBy = Automatic

	column ShiftID
		dataType: string
		isHidden
		lineageTag: fa33cab6-9a02-5583-88dc-5f5dd7654b22
		summarizeBy: none
		sourceColumn: ShiftID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		isHidden
		lineageTag: 17bd68a2-1c88-5e27-b07f-c26d8ad20673
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		isHidden
		lineageTag: 20457a94-0cf4-5d9e-bf3f-4e930048dddc
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column TargetUnits
		dataType: int64
		formatString: #,0
		lineageTag: c19df71e-88a5-5638-9aa6-61fc6c6dd2d8
		summarizeBy: none
		sourceColumn: TargetUnits

		annotation SummarizationSetBy = Automatic

	column ActualUnits
		dataType: int64
		formatString: #,0
		lineageTag: aa3898c5-cbbb-5582-a0e8-7131b4dd2be2
		summarizeBy: none
		sourceColumn: ActualUnits

		annotation SummarizationSetBy = Automatic

	column ProductionID
		dataType: string
		isHidden
		lineageTag: 289d17ea-a73d-598f-ac51-a397d79f46d9
		summarizeBy: none
		sourceColumn: ProductionID

		annotation SummarizationSetBy = Automatic

	partition Fact_Production = m
		mode: import
		source =
				let
					Source = Csv.Document(Binary.Decompress(Binary.FromText(Text.Combine({
							"fZ3drmU7bp3v/SxlQKT+LwN4XxhwCkZ+HsBwnLiBwAac9vtn1a41xqKGOKuB7nO6zncmtCRKogYp6u/+6a//8uMf/vJv//L3f/fjv//rX/73X19//a//9M//+vtP/vE//v1//ec///qz//FP//F//uWv//Pf/vLX//fjv/zzX//zn/7v779/E3/593/7+7/7Gy8+/rbY3xb/8Q/Ffry+9Prff7RWfqxf/y31xz/+t/LrP6bo1xstv7DxY/UN1BX9+UL9hdbyY/bxY5oDrSfq3w1ov7863V7oAtoU/XqjVn6M7T/GYAO6oj/f6KsBo+0fYw2g40TrdwNe/9S8/Ohr/hivr7/RqeivBvQ3OuqP7h3oUvTn+6uvPu2+frTFtu4Tbd8NmO/Oev366WirFUW/3ujrq+P1xTHRr2aK/mrAQg+M7154o2G0+mED5W0Dgw2oin59BvbbBj5tbYr+/FjWLxtYbQLtJ/qxAXvbQOHPGop+fczllw1M41enorABf9tAY1vXiX5soP62gd7YgK0obKC9bWCgAV4U/flG7W0Dk6id6McG2m8bGBvT0F3Rr/fA2tsGNozQq6KwgfK2gYm55WG0Bm0AA/ttAwa0K4p1ADbQiQ5FsQ74ex3obMA80d82UOM6gGnoS9GvN1rfNjAa0K2o2sBGA2o50dsGOLDVFNV1gNOwuqJYB8pvG+gNA1vrif62gffAfq8Dhp9Vm6KwAawDG6Zdu6JqA1xfaxiteawDlw3UqaiuA4XoUhTrAGzg09Z9orcNdPRrK4p+fdDvvWDDXJopqjbAJaP5iV57QWcPtKoobKDqOtCaorIO9Eq0n+jHBrAXGMylDUW/wsD+soGKfm1T0Z9h2/hlAwV7QQujtQ4bsLcNGHtgK6rrAJe3XhTVdWCjAd1O9LYBxyzorihswNUGelX0Z3AdXjbQaYS9nejHBsrbBhaGoHdF1QYK5lYfiv4MlvXLBrjF9Xmin73A3zZQ+bOWomoDnx7Yiuo6MNCAEUZrH3vB2x/YBQM7TNGvz+T+ZQO7oAHDFRV/YHb066gn+rEB+AMOcxlNUVkHZmMDuqI/g7l8rwOwgTFO9LcN9GAD3GPHVPQrDOzLBobzZy1Ff4Zt43sdgLmMfaLXXjA6GjCLorABf9vAQg9MUxTrAGyg8auf0TLPbGBNrAOzKirngrmINkV/flaX3zaAIZj9RD8+YdW9YA5F1QY4sHMqKuvAaBiCuU70YwPYC+jmzK2o+ISDa9YqimIdwF7ABiw70dsfmPhZyxUVn/DjQK+q6GUDMJcVRqseNvA+G87Fn9UV1b2Avssaiuo6MDBh1jzRex2o/FlLUfUJuRCtrejPcIT4PhtiddnlRD82YDgb4mdtU/QrDOz3XoBFc7uiP4O5/LIBzoJdT/RjAwX+AIxwN0XFJ5yNbe2KwgbsbQPcDXcYrXb4A/5eB7hm7anoV1gyvm0Aq8teiv78LBnfZ8PKn7VP9NYH4JK9/kDRr3Do/7aBBtQU/RmWjOgTWtAyvtGPDei5wIKW8Ua/guvwywaMDWiK6jpQBtB+ordPOCvQoaiuA50NmIrqOlCJhtHq6V4A4ceClmGnPuDQB97T0IKWYT07FywcoixoGXbqA+23DdBeLWgZ1jMbGJgFFrQM6+k6ADnJgpZhPbUB7AUWtAzr2dmwrQ50KHppRPxZ80Qvn3AZ0aXo10dO+vYHBntgK/rz89VfNtA3flbQMizXBzhhgpZhI1sHNrw3C1qGjfRsiM3IgpZhpz7QsA7wq01R0YgGhyBoGTYyG5jw4C1oGTbycwHbOhXVdcDZgKXoz+Bp/loHPug+0ftcwH6tRVFdB7hoVlP0Z3Aff60Di18No5WeCxYOpxa0DDvPBQZ9AP0atAzb2dlwOdF+opc/8FkHgpZhO9UJPw2YiupesGHaQcuwndsAG7AV/QqT+1sjAhq0DNuZP9AWVsKgZdhO9wKu2s0V1bPhIloVlXVgNDbgM1qvfxZt4K0PTKi6FrSMN6o28PnqUFTXgcHOmid6a8UD0zBoGW9U4wWdX92K/vxY1rcNcIsLWsY3evmEHQcTC1rGGxUbGIWoK6r+AMQUC1rGN/qxgbdW/JncvSkq8QJKCda7ohovgFRrQct49XemEdFeg5bxRr/CEeKXDVT+rKWoxow4WkHL+EbvsyEOURa0jDf69XEdjniBBS3jjf4M6PfZEBMmaBnf6H02/DSgKvoVZOVvnRBDELSMN3rFC2CEQcv4Rj97wftcMOiUjqHoV5jcK0jgNqaiug4MbEZBy3BP/YFOdCsqGtGCSGVBy/AzbljgD8Cygpbhadzw0wNBy/AzbuiiD1jQMtyPdQBxQ9pr0DL8jBu299mQO0zQMtzTsyHnVtAyPNUH2mYPzBO9z4ZOdCkqGtH8/Kyt6M/gPn6vAxitoGV4zeIFk5YVtAyv6V5QYdpBy/BTH3ivAwsHaQtahtc8XoCVMGgZXtOzIdfXoGV4zXTCPrEOBC3Da+oPNP6sqejlDxBdiopW3HgyClqG12MdgE4Isdp2UfQrLPDfGhFm7DZFJV7QN78aRmtkGhEDwha0DB/pXtDYgKao2MCsRPuJXmdDhhgtaBl+xg0N6wCGIGgZPtL8AQ5s0DJ8HHtBg1YMywpahufnAhzNPGgZnp8LIPx40DJ8ZP4AVV0vrqjmD2AaeqmK/gxy0q91AG65By3DZ74XONCuqOaQDH51KCoaEdMiPGgZPlN/wPizlqJfn2Pk75gRG7AVVRuA8+RBy/CZ+oSNqCmq6wDOsR60DJ9Z7JjrgActw2fqD0x+tSmq+gDOMG5dUdWIoOx70DJ8HTbg2AvYA1NR1YqhlnvQMnylNvDprH2i97mAnRW0DF+pRoTVxYOW4evYC+ATIsjqQcvwlfqESLbwoGX4ymJGHaEwD1qGrzR/AG6OBy3DV7YXTOdXh6KyF/Bk5D4VVX0AXrEHLcN3agM4mHjQMnxnGhF3bg9ahu/0bMg1K2gZfuoDLmdDD1qG",
							"71wrZgOqotc6AHMJWobvVCfEyciDluE7zyFhA4aiT1qxBy3Dc33A2YClqO4FC/Zat6KXDaBfg5ZRS+oP4FzgQcuoJT8bogeCllFLGjfkLAhaRi2pT8jRClpGLWnMiBMmaBm15OsA0XGi915gbOtU9CmHxIOWUVN9oA3+rH2iz7lk3ouiXyEQ9O0TYgi6KXqdCzANqWW45pQyXsAGVEU1XtD41aaong0329pP9PYJ6WdRy/CYUxr9Aa5Z1DJcc0qpFfNnrRP9nAsYN8SMpZbhMac06gM48Dm1DI85pTF/gJObWoZrTinjhpixwxVVnZD71qiKStyQWTQ+wmjVbC9Y9LNGV1TOhnPCtMdQVDUiJzpP9LMOVMkr9rEUveIFMMKxFb1yydADs5zopQ90ekTTFL00IljWdEXVBugRzXqid7yANjCborIODM7Y2RXV2DH7dYbRanleMRswFb3OBZixcyn687Nt/N4LYANzn+idP4Czoa+iqNoAZA9fpqhqRPQ0l5/obQPQ4H1VRdUnRMqRr6aoxA074jC++oneewH91zUUVX+AC9GaiqpWvNjWMFo9Oxsy+9PXVvQrXEUoISDsuyiq68Agaid6+QODnuZ2RUUn/AzsrorqOgCNyHc70ftcAJ3Qd1f0ihtiYPdQ9Ol+ge95opcNfDyivRS9/AH2wFZUz4bYOGsJo5XGjifaWospKnnFE5ZViyuqOSSFDagnmuwFBWhTVPOK4RXX0hW91gE2YJzonVeMuVXLVFT3gsavLkWvuCH7dZ/oHTOCSFWtKHrlEw6gpqjuBY1fDaOVxo6pFVeriqo+gANftaao7gW7Ae0n+vEJcTas/FlD0SuvmF+dikrcsH/QdaL3OsAJY1vRr3CE+LYBfNWLohozWkTtRJO8YvSru6JXPiG/WhVVnRAhm+qf0bI0drw4Db0rqvECYwOGomIDY/NnzRNNdEI2YCmq+kDlz9qKak4pzoa1lhO98ooH16xqioo+wLziWl3Rn2HJ+D4XYG7VeqKfdcAldlxrU1TjBZzctSv6lFNaaxgty2JGm9OwTkX1bMjRqkvRSydkD+wTveOGcPRqK4pKvIDyZ22mqPoDNJfmJ3qdDZkYUltVVP2BzgY0RVUnpLm0fqJ3zIgTpg1F1R+obMBU9NKKMQQtjFauD3Byt62oxo6h7NdeFFWdkObS7UTvXDKHaQctQ3LLETMqRKuiYgO8OFKDliG55ZpDUoOWkeeWUyOqQcuwVB9oUEhq0DIs1wcgANe+FP0KA/vLBpxDsBVVG4BXXIOWYTWzgQ0xpQYtw3J9gKMVtAzJLWcuGdoatAxLY8cDKUc1aBmWx46R7VGDliG55bx3zLaOE01sgJ01Fb3iBTDtoGVYTc+GNMKgZUhuOXxC+tqzKHrtBbDXaYqqT8hFM2gZklOKdYBOadAyJKeUuWT4WUHLsJHqhMjTrEHLsJH5A581K2gZklOKdWASnYrqPaPJfl0nmuQTsl+3ol/Bdfg+G8JcgpZh6bmAOaU1aBk20hySStQV1RwSZFDUVRVVnxB6Vg1ahuV3TunqBi3DZn6/AJ0VtAybabzA+LPmid5aMSd30DJs5ucColtRzSUjGrQMm+m9Y/oDQcuwmeYRcTcMWobNP/uEQcuwmdYfwP2CupuimkvGfWt3Ra/7hhjYoGXYSu+YcDMKWoatLGY0OWGClmErzSHhkhG0DFupP4BZ0IKWYSvVCTELWtAybOX3DQtQP9FbJ0S2Rwtahq00btjYgKao2gAKILSgZdhKzwWVXx2K6t1zhGxamYqqToiARQtaRsgtj+cC+IQtaBmSWw4bwNxqQcuQ3HLqhPhq0DJsp/kDTtQV1bghFqIWtAzL75xij21By5DccuYT8qtdUd0LcOJsQcuwVB/oxgbME719Qie6FNVzAe3VtqI/g5Tw7RPCCIOW4XnsGGtWC1pGnlvOgHALWkaeW05duwUtw0t+vwAzNmgZXvK9AJ0VtAzJLYdP+GnrONHbH6ANBC3DS6oRccYGLSPklkd/AKpDC1qGp7FjZlK1WhTVeAEO/a2aonouKETDaNU8doy2Bi0j5JRGrRjRnRa0DK+pTzjYgH6id/4Al7egZXjNbGB2olPR694xf9Y60VsrrvxZW9Gn/IEWtAzPzwVwSlvQMiSn9G0DPES15opq3JDra6uKqj+AbLoWtAxv+f0CtrUrqjGjwbYORfWeUWVb54necUMuGUHL8JbnE7KtW9FrHcDABi3DW55LhrYGLcNb6g/gbNiCluEtzynlV+uJJjEjok3R694xhqB3RfV+ASImLWgZnt85rUSnomoDXIiCluF53HBxCPaJ3vECmnbQMrznPiFRU1TyiBjdaUHL8DRu2DiwQcvwnuaUInzfgpbhPc8pZVv7id7nAtrrGIpKTumcbOtUVP2BjjUraBkhtzyeDQvRrajmkiEroQUtw3N9gNtG0DIktxx7Ae01aBk+0pxSJF21oGX4SHPJ2K9By5DcctYlw2gFLcNHuhcgbNeCliG55bxfwAbME71rUHByz6Wo2gCPO3MretUlQ78GLeMht5zHnaBlSG65S15xC1qG5/oAPc2gZUhuueYVt6BleKoPfBbNoGWE3PK4FyBNsgUtw2d6NuRCFLQMf6hJxbYuRfWOyeJX94ne5wKejndRVHPLuRtuU/Q6G8JeqWXUmE8Y9wJ6xdQyquYTYh2ArNyoZdSnGpV0SKhlVM0nhA1w1aaWUTWfEDGjzZ81FVWNiFICtYz6UKOSF3IatYyq+YTvvYAXyDq1jKo1KhE7hv/aqWVUzSc0sYFeXNGrBgUbUBXVdQASTS9htOof14FeuqKqDyyiQ1FdB3Dg62WeaOIPDKBLUdWKcd7qZSuqewHCdt3Kid73jOC7dDNFr3UADTBX9GdAv8+G/Go90UsjWs6vNkU1XtCJdkU1XsB+tTBa+bkAEZNuU1H1CQu/uhTV2HFjD+wTvfKIOLm7F0W1JhV/lpuiWocEDkl3P9HbBiDV",
							"dq+KXrlkmNzeFFUbwOm4ez/RRB/A5PahqOQV89Zt96mo2sBkD4TRymvVQvbovhW97pigrbUoetUpRWdVO9E7l4wrYXVF5Wz46axaFZUaFJP2WtuJJvcNYQO1K6pnQ+4FdSiqZ0P2a50nevuEnQ1YiurZkEZYt6J6xwTbcW9htNI7pxsKSW+mqO4FuBfXmyuquWRQHXqrJ3prRAi099YU1XXA2dauqNYh4b7VxokmtWrZgKmo7gWdP2spqjYw2YB9ook+gAb0oqjmE0IA7t0UvfKIYK89jNbOcsk2cqB7r4o+5ZD03hTVdQCCWu/9RG+tmEbYh6J6NlzsrKnoVZuOP2ud6F2jcrCztqKqFSNq1kdR9KpXjD122Ine+YRcs4YrqnVI4Jb3URWV2DEL9/TxGa2QTxjrD3Byj66o5JRS+OljKKo2UPjVeaLXXsCIdB9L0Usjgg2MrajGjNhZs5xoUqMSP2uaoppHhMS7Pl3Rp5zSPuuJJjWp+NWmqMaOK7/aFb1qVqNfZxgtS2tU0oOfU1HNH/j0wFL0qkfEIdgneucPQFDrqyiquWQI2/Vliqo/wPV1+Ykmd8+xZq2qqK4DqM7XV1NU14HCn9VP9M4jog2soajGCxCF6GsqqjqhEw2j5dm5YPO8tbaiei6gU7qLoqITDnrF2070PhdAoulBy7A/3zfsQcswz3VCzIKgZUg+YZP7BT1oGfbwhgWWjKBlSD4hYkbcjoOWIbVqYQNQdfteimr+ALe4vRVVnxCq7ghahtSqxdkQ4t8IWobkE/JcUIG6oldesQGtJ/p853QELcNSfYCuwwhahtU8h6QDHSd620AnOhWVPCI+TDGClmHpfcP2+eo+0XsvwCFqWFFU9wLsMMNMUV0HCr8aRmukOaVY4EfQMh7yCXGJcAQtw9I3LKg+jqBlSD4h6xXDXIKWIfmETfyBEbQMy+8ZYcKMoGVIPiFySDgLgpYh+YRN7hmNoGVY/oYFwvcjaBmST1jFJxzuimpeMaKRw6uiUo9ofhoQRmv+8c7pCFqG5BOyRiUGNmgZIZ/Qg0746ax5oknNathr0DIknxDngsEGbEW1JhXRoGXYzHVCtDVoGZJPyHrFsKygZUg+Ie6aTaL1RO87pzTC2hSVdYD3jEbtikq8gG7OCFpGnk/IqrIjaBmST8hzAX/WUvSqXc8G7BNNfEJ8NWgZkk/I2nQYraBlSD4h1gGcY0fQMiSfsErMaAQtw1Z+95xoU1TfsOD6GrQMySekRoQtrg1FL52QPTAVvfKIMAuCliH5hMgl4ywIWobkE6JeMb2MoGVYet9wcTMKWobltWjYWUHLsPwNC1weGkHLkHxC+IQQ1kfQMvJatSzYMYKWIbVqmUtGdCh61SuGaQctQ2rVsk4p9ti+FFV9wNlZW9GrXjHsNWgZea1a5hOOoGV4SbViKPsjaBme1qJhkuAIWsZDrVqcY0fQMiSfkPUH+LO6oroO4P7WCFqG1KrFXsDRClqG5/oAN86gZXh+35DbRtAyPNcHkII8ZlH00oiImqJqAwgzj6BlSD4hbABnmBG0DE/PBaxdP4KW4XkdEi7FQcuQfELWrkdnBS1D8gmxDnCHCVrGQz4hd5igZUg+IWrRcHUJWsZDjUqIfyNoGV7zWrUYgqBlSD5hkTetxnJFxSdkIGisqqi+afVBw2i1dB3gFhe0DG/pu2ZIYhlBy/C8Dgn3raBlSD4h4wVs61JUc0g4uYOW4S2zAYqqI2gZT/mEmFtBy/CW7gU8mAQtw/O4IaI7I2gZ3vK3bGCEuymq/gACbGN3RVUn5OE0aBmST8jadOyBqajeO6ZTGrQMT9+woKY5gpbxlE/4ntwzaBme1iHhndMZtAzv2X1DFuyYQcvwnuYRwQZm0DI8f+MSW9wMWsZDPiEKIMygZXjPa9dvoEPRK2bUgU5FdR1ADskMWkaeT7gbf9ZWVPOI4LvMoGV4/sYlbGAGLcNH6hPyZwUtQ2rV4n5BJ1oV1TuncEpn0DIkn7DI2XAGLeMhnxAq2Qxaho+0PqGxB+aJ3rnl0F+nLUV1L0A4dNpW9MorRgOCluH5fUMsRDNoGZ7qAwwIz6Bl+ExzSo1frSd66wONaFP0WgfYgK6oxo6dXx0nmuSUEp2K6joAN2cGLcNnXouGbd0neueScXmrRVHVByB/zmqKXveM+NXPaNWSxguQ8TODllFLnlOKzgpaRi2ZRsSUoxm0jJrWIWGd/Rm0jJrfM+KqHbSMhxqVn5+1TvS2gcqvbkUvnxBtDVpGLWltOvZA0DJqSe8dw3ubzRVVrdiIVkWvdQA2ELSMavlbNlgygpZRLY0dczcMWka13CckOk/0OhfwhZwZtIxqqU+IJOwZtIxq6V6A3PIZtIyaxw0RPZ9By6iW6wPo16BlVMvziPjVeqK3PoBzwexN0as2Hb/aFb1ySmGv1DLa3xZLc0gKGzAVve6eY+OklkFUbYAOCbWMN5q8ew6UWgZRjRnBf53UMoheb17DtKllvNFbJ1xsQFVUbQA3rSa1DKKaV4x0k0kt443e947pko2hqNYp5VI8pqKiDzCHZI4wWjPVB5zoVlTvnCKfcM6iqNam47417URvnxCqw5yuqOYRQSOasyp61SvGz5rtRJPccra1K6r5A4MNGIrK2ZC1aOacJ3prRDSXuRRVn7Dzq1tRySnl8XyuMForvXfMJWOZohozorO/XNGnmlRz1RO9z4b0iFZTVPIHeNFprq6o+oTQiOYaJ3qvA7SBNRVVG6BDspaieufU2Vn7RO+aVNxhdlFUc0p5hNimqNas5ia/w2il9QeYWz53VVTrE3Il3E1ReeuWctLc/UTv2nTId5l7KHrVLWdbp6JqA43oOtFbI3L+rK2o1iOCQ7JKUfRJK17FTvTWiNBZq7iietcMe8EqVdHLH2BbP6P1lE/YgXZFNY+osq1DUa1DgtjGKvNEb5/w0wNLUa1Vu4huRfVtOySzLSsnetemQyWWZaaong0LUVdUdcLKBtQT",
							"ve6c0n9d1hS91gGiXVG9X4CrtMvCaOV1y3GSXzYVfapbvmwpqvoAEkOW7RO9a9FwwnhR9MofgGm7KXq9bYcGuJ9okk+IfvWq6JNGtLwper1v2ID2E71zy51fHYpeb92yrVNR8QmZMr88jFbL9wL261ZU1wFEd1Ytil5vWKCt1U70jhcsftUV1XxCXPtdtSqqMSP+rNpO9Pnd81W7olKLhtnKqw5FNZ8QXvGq80SvmNFCxs+qS9GrXjG/uhVVf4CLZguj1fOaVERNUdGIeC5YzRXV+oRQ9FarJ3rfM+IsaE1RjRt+vtoVlXWAXvFq40Rvn7DyZ01Fr7tmE+hSVOsROdu6TzSpP4Ae6EXRK68Y9tpNUd0LKtEwWg/xAjagKqr5A7Ss3hS93rDAjO39RO/6A5yGQcuwPF7AvSBoGfLmNdYB3ONcQcuw/J4RTTtoGZbHC+BprqBlSD6hi1a8gpZhed1ynA3XcEV1Hej8alX0qS7ZClqGzdQfYL8GLcPS+gPz87OGoppHRPcxaBlSnxB1SqFprqBlSD4h8wf4s7aiqhFxMwpaxlN9QsyCoGXYzGvTobOClmEzr1GJHghaxkN9QtrrbIpe5wJ01uyKPr1zuoKWIXlELvrAClqGl7w2HYYgaBmexgt4E2AFLSOvS8ZHjFfQMvzhXIC2Bi3D83gB/YGgZXgeL0B9lxW0jDyPqCF/YAUtw/N4Ac8FQcuQPCLoA58GDEWvPCJ21lRU65TSdwlaxsOb14Nf3YpqzIgOdNAyHt68Rjx2BS3j4c1rHiGCluF53XJINCtoGZ7eM/qsA0HLcMvrkmGBD1qGW7YXtM0GDEUlXsByFStoGfmb18wnXHspqjUoeDbcW9Grbvl7FuygZbinOaXogR20DPc0jwib/A5ahrx57XLveActw/O65ZNtbYo++YQ7aBme1yGBm7ODliFvXhfRB3bQMjx/1wzrwA5ahj/ULWcD9ole8QJmfW0rimq9YiNqimrseBMNo1Xz9wvws4KWIfmEWAewvO2gZeRvXvOFnB20DM/vGTWiQ9Err5gNmIpeb1yyB9aJ3jkkxq9uRS+d8L1q76BlSD6h1h/YQcvwtG4541vbXVHViDobUBXVPCLshjtoGZJPWKUGxQ5aRl6fkAv8DlqGt/z9AjZgnmhSrxijFbQMb/k7JhitoGVIPqFLLZodtAxv+bmAqCmq6wC24x20DG/pueDz1XqiiVbsQJuil0bEr3ZFr7pkRMNozTRmhBDjDlqGp3FDSgk7aBme3jOiALyDlpHXJeOd0x20jIc3rxE120HLeKhLhuSgHbQMqUv2Xgca0iJ20DLkzWv4A5wFQcuQPCLWJ8QOE7SMkEcU8wkXe2AoKv4Ac8l2m4ped05hA0HL8DxuyO04aBny5jXvF6AHgpYR3rw+alCgX4OW4SvVCWmEQcvwld4vwAWyHbQMz+OGOEjvoGX4Sn1CWlbQMjyPG9J5ClqG53XLOQuCliFvXjNegNHqS1GNHRt/1lZU84iQbrKDluE7zx8gaoqqP1CIuqJXPSLYa9AyPH/XDGeYHbQMT+OGrN6/g5bhedwQetYOWkb+5vXgAh+0DN/5XTMMQdAyfOdaMdaBoGXIm9fQiiEl7FkUfapFs6cpqj4hDnw7aBmST0iNCD8raBny5jX2Ajp6QcuQN6+b1KjcQct4ePOa+1bQMmqqD1BW3kHLqCX1Bxp7YJ3otQ7wYt4OWobkE3IdwM8KWoa8ea3vmOygZdRcH0DEZC9XVPcCSOB7VUVVH+DyRi2jP711C4FiU8vosTZdtIFPA4aimkOCPM1NLaM/vHXLIkObWkbX2nSoQwKVbFPL6PrWrSNeAJRaRn+qTUfLopbRY226I4+IqCt6vV8Ay6KW0WNtuiOXDJa1m6KqD9Ar3l3Rx3PBDqPV0/wBno73VFTfMeECv5eiEjteHK29T/TxjcvXv1oU1b3grTq8UFP0yiueQP1Ek5pUBWhVVNeBd9GWF9oUveoPONB+opdGhJuBr/8/FNWY0eLPmorqu+fvIMALDaM1Un9g8mdtRfWOiWO0rCh6xQ3xVbMTTe6cVqCu6JVHxK9WRdUGFobA2okm/gC/2hW97pphtGwoeumEDeg80TtesNmApaieDSu/uhW93rwG6mG00rPhLkRNUb1jMjFh3BXVHJKJIfB6osm757Asb4pe9QfYgK6o5hF19KuPE73PBRNG6FPR6207zC1fil51yfiz9okmd06B1qLo9a4Z+rWaoroXcHmrYbRWqhO+CyC80KrotQ6gB2pTVM8FjWg/0VsjGvxZQ1H1B7jA16mo1idsMO26TvSOGXHC1K3oQ00qK60oqjphgxE2O9GkZjVGq7mi1xuXaGuriqoNGNHPaMlbt37eNXuhXVE9G3aiQ1FdBxo7a57onVvOLa4tRaU+4aQRtq2o5pAM9EAvJ/r4xuULNUV1HaANdFf0escENtDriSbvF2CH6U1RvXfM3bB3RR/yiF5oGK38rdtNdCqqtWg2RqsvRfVcsGEufZ9oUpMKPTCKotc6gEVzmKK6F3AdGH6id04pd+5RFb3eN0RnjaaongsqdpjRT/Q+FxgsawxFr3fN2NapqK4Dm18No5XXrqdlja2o3j2nBz+LonrPiG7OtBNN9AHYwHRFL52QX62Kam06+gOzneh995xr1uyKqkb0QYeiqg/Q1Z3zRO9zwcTcmktR1Qc4DedWVHzCSQ9+hdHqaQ0K+oTLFNV4AQd2uaKXRoSBXfVEbxvgbhi0DOv5m1ZYXYKWYT2PG7Kt40TvOiSFnTUV1VwyuuVBy7CH+gMYraBlWE9zyWgDuyiqd0751W2Kal4xD3xBy7CV5xHhZwUtI3/nFO8dv9CmqNYppU8YtAzL4wXGnzUUvd4958+ail7vmsFcgpbx8M4pT/JBy5C6ZEXWAQtahtQlK2cu2Qu1E03eL2hAXVGNF7zzX19oVVTjBca2htHK65K973G+0K6o7gWwAQtahqX3jCZkDwtahqXx",
							"Au4wFrSMvC4ZF3gLWobttA4JXDILWobtP+WSvVBTVO+eL/Rr0DIe6pIVdFbQMiyNF0D+fKFNUd0LsHGadUU1btj5sz6j5Wm8YMPXtqBlSD4h7h0P/qylqJ4LNhuwTzTJI8LPClqG5BNW0QcsaBmexwsqRitoGZ7WLR80wqBlPLxz2tnWpqjeMcHZ0IKWIfmE8Acc/epDUdWIsHObT0WvnFIsGUHLkHzCgnpERLeiV+wY/Rq0DLd0HcB5y4KW4ZbeL+D6GrQMt1wjIloV1dzyirkVtAy3vHY9bCBoGW5/PBdY0DI8rVtOjciCluEPd88xBHUpqu8ZFf6srehVjwidFbQM97w+Iew1aBmev2uG444FLUPyCbkXoAeCliH5hI6YEeZW0DIe8glx6LegZUg+oeSWv9Bxorc/4BiCoGW4Z/eMKABb0DLcc58Q5hK0DMknRP4AdG3rRVFdB2hZ3RTVdYA7TNAyfKQ+IaQEC1qG1KRirVo2oCmquWQ0l6BlPNSk4r4VtAypSdXONy5f6FRU9YHJtq4TTWrTwVyCliE1qYquA0HL8PSOCa6nvlA70TteALfchit63S/Azj2qotcdE3RW0DIkl4y1aDANg5YhNan8rD/wQoeikls+6GcFLcPTGhTUMixoGZ7XrK7sga2oxo5xhLCgZUhNKjvzCV+oKao+IURVC1qG5JIhn5C+dtAyHt645Ooym6KqFdOyZldU37LhaAUtQ3LJWLueP2sqqndOEVqwoGVILhnyij89sE/0vmdEXztoGb7S2vVcXYKW8ZBLxm0jaBmenw0HFs2gZfhKteKBCRO0DM9rUHAIgpYhuWTMI2IDhqL6hsUkOhXVPCIu8EHL8J3mE3K0gpbhO98LMA2DlvGQS8bJHbQM35k+QCnBgpYhuWSwAQjrFrQMySVTrdiCluE71Yo/X+2KaswIypMFLcPzGhTOHpgneq8DXLP2UvS6Z4QZu7eiD3VIXm3HaA2tSQWtGL62U8sYsSZVzC0f/KorKvcLuHM7tYwRa1JFG/igTdHrzqkD7Yped8/Z1nGidx4RbMCpZYynmlSFbV2Kam45dkOnljFiTaroD+B07FYUlXgB6me9UFNUc8s5WhZGK3/vGP6rW1VU7xkNNqApqjkk8LXd+one+QODDRiKXu+a8atT0Yf7hi90nWiSP8CvbkWvd0zei6Z7UfSqVzyB2okmtenQAHdFtTYdbcCromIDzEpwD6NV/3g2dO+KXveOMVo+FFV/YLIH5ok+1iN6oUtR8QcYWnDfiuo7JjTtWk709gdwOPVqimrMiKtLdUV1L2Bbaz3RJJcMnVWboppPyMldu6LXe8ewrBpGq+W1aLAX1KmoxoxoLnUpKrFjJDa/0H2iyTsmsNdWFNW3bqGSeTNF1R+AWO3NTzTJK8ZotaroddcMndWaoppH1NEDrZ/onVte2ANDUb1rBrne21RUtWIoT97CaKVxw8nVpW1FVSvmLOhF0eveMVE70VsrxjnWuyuq64Bhge9VUY0bLqLtRJM3rzFavSt6vXcMG+hD0WsvwITp80Tv+4b0B/pS9HrXjD9rK3rVK4YNjDBaK90LaK/DFNU8Iu4FwxVVrbiyAfVE77ziT1uboqoPwNn30RW9zgWwrDFONKlNh9EaU1G1AcjKPpaiuhdwdRn7RG9/oMCyZlFU9QGc4nyaomoDXAdmGK2dnQsYM/JZFb1qVqNfZ1NUa1LRBmY/0cc7py90KKq5ZAjZ+JyK6t1zjtZcJ3r7hMhM8bkVVY0IcpKvouh19xz2uuxE73xCDsFyRSVeQGHdV1VU65Ry31qf0bL8PaNBtCuq9wu4aK6hqGrFDbNgzRO9/IHP8raWolqHBMdzX1vR610zDMEuJ3rfL6hETVG1ASQH+XZFtV4xEm581xO9bYBb3G6K6l0zDuzuil75AzCXHUYrr1uOlE7fU1GtWd3Y1qWovm9In3DvE01q0bz7tQYtwx7ihhOoKXrpAwuon2gSMzKgVVG1AeRn1aBlyHvHmktWg5YhOaXUB/jVoajGC2DatUxFVR/AUlyDlmGe64Tsga3oVbv+bQM1aBmWxw3hZdSgZeTvHTMgXIOWYWnckIGgGrQM8zx2jCEIWobl+gCCVjVoGZJTipgR8l9r0DLM8zwi9sA80WQdYAOWoroXfNCt6HX3HDYQtAzJJ2xyNqxBy5B8QtgAYvI1aBnWMxvA23YvtJ7o/YYFFs0atAzrad1yyPU1aBmW3zWrbMA40bsWDU07aBkP9QnhD9SgZUg+Ic+GHIJ9onceEdKjai2Kai4ZBLVaTVGtR8TJHbQMG+nZEIJaDVpGqE941KSCDQQtQ+oTmmhENWgZD/UJIdXWoGU8vHf86YGpqOYVO7+6TjTJKya6FZU8IhQdtBq0jLw+IeMFNWgZD+8dcyFqrqiuAxN7QauK6rmA+1bQMuS9Y2hEH7QrqnfNBn/WUPTKH2BnzRO9bWCyB5ai8oYFIyY1aBn5e8eDMzZoGfYQO4a9Bi3D8veMaC5By5D3jl3OhjVoGTbTPCIuGb0pet05xWj1rqj6hDht1KBlPOQVb/6sqajmki2sLkHLsPSuGV7OfKH7RJM3rWDaQcuQ945Rmw4JNzVoGZJXLPUHXqifaFKXDJ0VtAxbaQ4JUg9r0DJspXdMcDKqQcuw/K7ZYA8MRTVuyE1+TEXVJzT+rDBaD/oAJkzQMiSvGGdD7rFBy3jIK0bAogYtw/L3CzgNg5YhecVcB/CzgpZheR2Swa+2E71rVnN1CVqG7XQdoEcUtAzL65DgZmANWobkFSOXjM7TXIrq2XCwX7ei15tW+FlBy8jrE+I9oxdqiuobFjyYBC1D8gn5lg1GK2gZ7n+qWf1Cm6LX+4bogaBluKfrwGADxoned8+5DgQtw/O7ZoU9sBTVsyE3+aBl5PUJqZLVXRTV94zo6G1TVNYBSuA1aBlSn/BtA7zLW4OW4TX1Bz5tbYpeOiG/2k80iRegs4KW4TWNHSN4XYOW4TV/",
							"x4RfXSea1Cllv25F5VzAy0MtaBkP7x1j525By5D3jlmTqgF1RdUGKhtQFb3esKhAw2g9vHdMtCuqdcuhOrSgZUh9QtYtJzpPNHnDwoAuRa/3C/jVrajGjKARtaBlSH3ChvcLOlBTVNaBhtWlBS1D6hMiXtD51XqiyXvHbGtT9KpTih6wrqjmESFi0oKW4T2rQ0LhpwUt4+G9Y0yYFrQMT+OGPPS3oGXIe8fUitHWoGV4HjfEeasFLcN7GjPCvtWCluF5LZqC0Qpahvf87jnRpuhVfwD9GrQM73/UiJoPRTW3HCpZ86noVauWPRBGa2R3TPanB7aiDzUqrQUtQ3LLsQ7guNOClpHnljMY2IKWIbnlRWrRtKBlyHvHTXJKW9AyfKT5hJAUW9AyHnLL4Tq0oGX4yGtSYbSClvGQW85ZUJeiWn8AYeZWt6KaW85pGLQM33k+IUYraBmev2sGR68FLcN3+u45V5egZUh9Qu4F+FlBy8hzSlHe+oV2Ra93z9GvQcuQnFLeN4S5BC1Dckr5jgkbsBTVu2bcjoOWIfUJ4RPCg2+9KKpnQ07DborKuYCnuBa0jPrwrhnaGrSMmt83/Hy1KXrdOcUsCFpGze8bImjVgpYh9QlN8glb0DJqGjfkRdIWtAx579gkXtCCllFLdvd8cNEMWobUJ6xyz6gFLUPeO2YdEnTWcEUf3jF5oVXRqzYdG4DRmjGvOJ4LuMlTy5hPb912tnUoqucCbnHUMqa+ddvOWrUvdCmqPiH9AWoZM+YVH/WK0VZqGVPfujWpSdWoZcyYVxzXAfpZ1DJmzCs+9gKi9UTvvQCSYptNUc0j+rS1K6rxAq5ZM4xWft8Q0fM2p6JXjUpMw7kU1fsFdHXnPtEkXoDRWkVRjRtCqm3LFFV/gK7D8hNNcsvxs1ZVVGNGHNjVFL1ySvnVfqJJPiHbOhRVrXiwB6ai1xuXbGsYrVQfYHJQW1tR9QegD7RdFH145/SF2okmNathA9sV1XdM6D7uqqjoA5Or9m4nep8LoJC03RXV/AGayx6KqkZEe93zRO+4IW1gL0U1f4ATZm9FdR2AQtJLGK2RasVwnnoxRfV+AYagF1dU37RyNqCe6H3HZPCrTdErZtSBdkVVJ8QW18s40WQvGECnopdG5ECXoledUv6sfaJ3HRJINN2KolfteqKmqK4DuKbeLYzWTH3CTwOqonq/ACfObk1RrUGBKG+3fqLP9wu6DUU1drz51ano9ZYNBtbWiSa5ZBhY24pe946BelFU8weg7He3E71jxyhX0d0V1bMhVpfuVVG9Y1KJhtHK84qRQ9K9K3rtBRvoUFTuFzAi3X2eaGIDbMBSVGvVcm75VvTKHwBay4nedUhoLtUUfdKKe3VFNWbENavWE01qVLIBTVG9c4p4Qa9dUa1bTnutYbR2FjvGo1ovdCqq946N6FL0yh/AwNZ9olduOUvw9lYUfXjz+oWaolfNarS1+YneewEckt6qote5gF9tisr9ggY5qbd+oh8b4JtWGNg2FFWf0IlORVUjKkQ/oyV5xXzLhm3dimouGVftXhS97pphYLud6K0TIr7VuyuqPiH7tVdFNV5A36W3E731Ae6GvSt66YQwlz4UVRvY7Kx5ove9Y2cDlqJao5KrS9+Kam06ZHv0EUYrPRdsHHf6MEWveAEaMFxRrVOKI28f9USTvGIMbNAyLL9vaPxZXVGNG3LCBC3D8nMBYnE9aBny7jnfvIYNBC3joUZlZw/sE739AdwM7LMoqndMuB1PU1R9QlpW0DIsf8OCDnTQMqyl5wJ6mkHLCO+ex3WAp42gZVjL3y/gV4eiT7nlPWgZ1rK9gIWoe9AyrKV5RHTJgpZh+RsWNMKgZci757x7jh4IWoblcUO6OcsVvXLJiFZF9WzIyR20DMvfsMAVjx60jId3z+lnBS1D6pSaxAt60DIkr/g6GwYtQ+qUYi+A6tCDlmFp3JCpXD1oGZJXrHfNetAynuqUol+DlvHw7jkClz1oGZJXzHrF/GpT9DobYiHaXVGJHVP+7EHLkHfPmVtOdCr6dM+oBy3D8ppUdHOClvGQV4xtYwQtQ/KK9f2CEbQMe6hJtYH6iV46IbOVR9AyLH/DAnL9CFrGw7vnnwb0E73fOd386lBUc0g+X52KarwA/sAIWoalb1gwf2AELUPyijVmNIKWIXnF2Avg7I+gZUheMd85daCu6FWXjF+tij68dftC24kmMSN0VtAybP7xjskIWobkFct7xy90nuilE7Iq17Cl6FWzGqNlW1FdB2gDQcuQOqXwCZHxM4KW4fm5AL72CFqGl9QnRNhuBC3Dyx/vF4ygZUidUtrABNoV1fqEnx4YJ3rfL0DK0QhahtQpZQ4JG7AUvXLJYIRBy/CS7wUY2FoUVY2Ii2Y1Ra+37QbQMFqW+QPr04CqqOaQwHcZQcvwvB7RYgP6id7+AHIdRtAyPI8b4hQ3gpYh7543uWs2gpYhdUqL1KYbQcuQd8+1BsUIWsbDu+fsgaBleH7f0PlVV/R66xZD0Kqimk/IyR20DKlTCo0IO/cIWobkFbvUqh1By8jfPedl4hG0jPzdc57iRtAyHvKKJxuwFdX8AbY1aBme3jdsH9QUVZ8QR4gRtAxP6xF9/IGgZTzkFeO8NXpTVP0B6AOjd0VFI6KeNYKWkb97vowNmIpe6wAmTNAyvKaxY9pA0DI8jxvStIOWIXnFfNsODQhahrx7jr0A0tcIWobkFWse0QhahudxQ/qEQcuQvOImd81G0DIkr5gxI6JD0av+ANGpqN4voKsbtAzJK2bsmOhW9HrnFOYStAxv+Vu3GK2gZXhL/QGIfyNoGZ7qAxRVR9AyJK+4yH3DEbQMb+leYGxrV1TXAaRHjaBl5O+es4TZCFpGyCs+alBg1Z5L0eutW/6srajuBfTegpbh6X1DZqiNoGXIu+esXQ8jDFqGzyx/gDlPI2gZnr9tx507aBlSq5ZaMRvQFb3eusUQBC1D3j3HOkDnKWgZ",
							"+bvnnc5T0DKkVm3DuYA/a5/ovQ5wydhFUa1JBdVhbFNUY0ZQH0fQMvJatQtiyghahq9MK+aDdSNoGVKrFrlk3DiDluH5fUMuxUHLyN8952MPI2gZvvK3bNiv60RvG0AQYAQtQ2rVNskrnkHL8JXphJQUZ9AyPI8bwh+YxRW94gUDaFX06e75DFrGQ63aSbQrqnVKIVTOoGVIrVo737x+ofNE77rlhV9dil616RzoVlT3AijQM2gZkldcJG44g5YhecVYB+CUzqBl5LVqG6bhDFqGP9w3hGVZU/TKJWMDuqJXTaoO9DNaklfMumQYgqBlSF4xY8fsrKXoU+x4Bi1D8oq1BsUMWkYt+Vs26KygZci75/rW7QxaRv7uOW+HzqBl1DxuCK94Bi2jpvoA3zOaQcuouT7g/FlDUT0XYDecPhW98gn5s8JoWWoDjV/dil7nAoxW0DJqWo9ocR0IWka17H1DXp2ZQcuoluaSYS+YQcuolq4DOJrNoGVUS9eBwQZ0RWUvaIs/ayiq9Qk5YYKWUS3NHxj8WUvRqzYdf9ZWVM8F8IgmtYz1VKsWh6hJLWPFnNLsDYtJLWNpTilrUvGr9UQvfyA0oCmq9Qm5ZFDLWDGntCX1Bya1jPWQU9rgkExqGUtzSk3qlk9qGeuhVm3jZkQtYz3llEKBnr0oet05RWd1U/R65xT22sNotdQn5OTuVdGrXjHW194UVRvgmtX7iSb1B/jVoej1xiXRqajeL0B+1uzrRC+fkNkes29F1R/gAj+KoppbjhPnHHaiSZ1SdNZwRa8aFGxAVVRrUqFuzhxhtB5qUsFeR1dU44aLDRiKXnXJMFpjnuhdk4ozdixFNV7AbWNsRa98Qnx1lhNN8gfQWdMU1fwBnOTndEWve0aYW7Oe6J0/QOdpNkW1bjndx9kVve6YoLNmGK2R2wDsdU5Ftf7AZr8uRa93z7G+zn2it0/IRXMVRVUfoPO0TFGNHUN1mMtP9FkjmqsqqjWpaFmrKaoxI3bW6id63zNCWu9cQ9HrXMAemIped88xBCuMVp5bjjt8c21Fr9p0+OouikrMiFcR5rYTvfcC7rHbFdUaFHTLd1VUY0ZcX3c70SuvmBG+ubuiUoum8RC1h6JXbTr+rHmilz7Aa5RzL0W1Nt0muhW9alK927rKZ7Ss5PECB2qKXrXrC1BXVP0BrK+r1BO944aTbW2Kqj8AqXaVruiVUzqBjhO93zl1tnUqqvkD8F9XWYpecUOi+0Sf6xUvK4peuWRoq5miqhPCJVsWRsvy2nQYAquK6rkAh6hlTdHrzqkB7Sd616BAtseyoajGC2ivNhWVcwFrpixbJ3rlkPClgWVbUdGKG+Jby4ui6g/gaLbcTvSuRQOndLkrqjGjQbQqer1vyLaG0fK0DgnWrOVdUY0ZsV99KHrVqMTA+jzR57dsli9FJXZMnXD5VlTzipHEsmo50csnZPbnqqao+oTQNFd1RXUvwMFk1Xqif1gHalNUY0acBbUrKjphR3hp1TBaNfMJ+bbdqlPRp7duV12K6j0jOHqr7hO965Lh7vkKWobl+gB27hW0DMkthz+AI+8KWoblb9mwrUHLsDR2zHpEK2gZklte5K7ZClqG1VQjQorcakNRjRkVfnUqqjbA5S1oGZbrA1wygpYhueVNcstX0DKspVoxvxq0DMtrUiFks4KWkeeW857RClqG5Ja7vGWzgpZhLbcBol1RrUm12NahqOaWI8C2gpZhLX/nFNOwL0Uvf4Bf3Ypq7BgO9ApaRl6rltkeK2gZklPaJIdkBS3DZv6OCToraBmSU+qSV7yClmH5uYDLW9AypFatyTunK2gZklMKjaixAVPRq2Y11qygZTzklOIQtYKWYTP1B/izZlFU9QFk061pimp9QoSXVtAyQq3a6BNyKQ5ahq1UI2JnBS3D0junn2kYtAypVUufELMgaBlSq/Y6FwQtw/K3bDrbuk70Phd8emArqusAXYegZVgaO25cCYOWIbVquRfAXpcrqndOcfN6raro9aYVOitoGVKrVusTrqBlSK3aIjrhClqG7fSeEQS1FbQMS++c8vLQClpGXqt2dH51Kyo+IesRraBlSK1a1qiEDQQtI69V2xCTX0HLsJ3eL6CvHbQMqVVrUrd87aao6gP0XXZXVO8b0ssIWoaXrAbFZzsOWobnb9nQIQlahqexY95oX0HL8PzOKcIgO2gZ/hA7dqCmqN4zgv+6g5bhJa1Fgy1uBy0jzy3n2XAHLcPzt2w6f1Y/0TtmZESHonq/AEOwy1RU/IGO1WUHLcPTmlTMH9hBy/BUH+D7hjtoGW5pHRIconbQMjx/ywZLxg5ahudv3W5+tSqq75hgddlBy/C8JhW8tx20DLe8RiUsK2gZbvm5gJ01T/S+Z7TY1qXoddesA92KXlox0KBleEv9Adpr0DK85f4AjDBoGZ7HDfmzgpYhtWqRP4Bo5A5axkOt2ka0Kyr5Ax3pfDtoGXlOaUMm1Q5axkOtWg5B0DIkp7TJPaMdtIyHWrVwSHYtil616TBa1RTVmBHSenfQMqRWLX1CDGzQMvJatZNLRtAy/OHOKdF+ovc6wAU+aBl5rVqGxHfQMqRWbZW84h20DM/jhlzegpYhtWqr3DveQcvIa9U2eBk7aBlPtWoxWs0V1TsmNMJWFVWtmHMraBlSqxY20NiArqjmknHnDlqGj9QnhJuzg5bhI3/rlm1diqpPONnWrajGC3Ay2kHL8JGfC2CvQcvwke0FTBbeQcvwkfoDKNqyg5bhI80fGESbote5AOtr74rqnVOOVtAyfKbvmHCBD1qGp/oAn5jcQcvwmdnAcrZ1n2hShwQNCFqG5JYXuWe0g5bhedwQ8ucOWobn+sCnAVVR9Qk/DWiKauy4Ee0nmtQjQr+Ooei1DqBfx1RU44achkHL8PwtG07DoGX4StcB6C47aBmev2UD4WcHLcPTt2556N9By/CV1iGBULmDluHrj3VKd9AyPH3Lhi+Q7aBlePrW",
							"LQvQ7qBl+Mr9AUzDoGVIbjnWAS7wcyl6vWnFBmxFr5gROitoGdXSHBLuBUHLqA+1amEDQcuolmvFROuJJrVq2YCmqL51y2kYtIyaxg3HpwHjRO+9oBKdiur9AsSOd9AyquX1B7DDBC1DckpxxwTa295F0SuvGA3Ypui1F6BfqWVsrVdc1QaoZexYrzjGjBCF2NQydqxXHPOI2K/UMrbWK666DlDL2FqvGGdDmja1jB3rFR85pWzAOtF7L+Chn1rG1nrFzCv+vWR4oZaxtV4xfMJ3v75QO9HrXIDJ/UJdUT0bvreNF1oV1Tunkw0Io5XGjpEF/kK7otc7JmzAUFRrULz3rRc6T/TOIXmb9gtdil7vGzagW1H1Cd/rgBcrJ3rFjJAw/kJNUd0LKkbLXNErl4xfrSd61SUbHAJrimrc0NmArqicDXE38oWG0crrFVeYtk1FdS/4tHUpqu+cLrZ1n+i9F3C0vCiq5wLagJuiYgNQyV6Un+idS8bR8qqong0L0aao+gMd/er9RG9/YGDG+lBU44Y0Qp+KXvECNiCMVsu1Yv6srej1xiWGoBZF9V2zAiOsdqJJDQqsLtUV1fcLGnqgVkV1HVhsazvR5C0b9EDtiurZsMGy6lBUY0aGlbDOE71jRsbOWopeNSjYgK2o1qLhZtTCaM0sfwC1aF6oKapv3X5QV1S1YkO/tnqi933Dih5oTVF939DRr60rqueCTnScaHLvGJbVpqJXTSr2wFJU754bTLvtE71r13Nu9aLodfccndVNUT0X0B/oYbTye8cdbe1VUb17buiB3hS93jFBv/Z+oncNClpWH4pe9QfgOvSpqN4165gwfZ3ofcfk069bUc0npO8yiqJ6LmhE7USTmBGGYLiicjb8dNaoiuq5wNADI4xWGjtGkcwX2hWVmNHgHjuGotcbFpiGY57onVPKvWAsRfVcUNmvW1GNHW/MgllO9M4pHWjrNEUvfQANmK6o2kAhWk80ySmFEc6m6FWzmm3tiqo/ULEUz89oSW456xFhCOZUVHTCz0I0l6Jau557wdwneu8FA+gqimo+IefWMkUvjQidtfxE73pEnNyrKqp3zbhzr6bodfccRrj6id53zyf2gjUU1bMht401FVUboLmsMFp57Pjzs7aicr8A7xd42UVRjRdwCLad6HXveHKHCVqGWZ5Lhn4NWoY9aEQY2KBlWH7vmN5b0DLM0ntG3DiDlmHpe0aN562gZZil9Qnp6u6l6JVDwiHYil51SN6dZUHLkJxS1qJxoKboFTueQF1RjR1vfrWe6P2OybuS4Attil616RbQruhVg6IDHSea5A+ws6aiV7yAPbAU1Vo07xTkF7pP9F4H3mlnblYUlTetIKq+UFP0esekAA2jld45hfj3QquiWre8oF+DliH1iuETFv6sfqJJrVqYS9AypF4x9wK2dSoqOSS4SPpC14km7xewrVtRqUHRaIRBy5B6xdgL2FlBy7D0zumgEboret05xcB6VVR1wsEGhNFK6xVTH7CgZdhI7xtuokNRvWNSMFpBy5B6xYgZLaJL0atW7QC6FdWcUn41aBk28jeviZqi131DNCBoGTZSrZhzK2gZUq8Y6wBXwtoU1b2AS0btiqo/gD3WgpYhueWsQ8KvTkU1h4RGGLQMe3jPiD9rn+idQ7Jgr0HLkNxy1QcsaBlSrxg2APfRgpZhM7WBzgZURR9iRi+0KaoaESdM0DIsfc/os8W1oeiVR8QemIpqPSJO7qBl2Mr9AdhA0DIsfc9own20oGVIbjlrUKBfg5ZhuT6AM4wFLcNSfeCzugQtw1ZqAwVGGLQMyS3H2ZCzIGgZtnKfkD0wFNW9wInOE03euMRe0Jei15vXbOtWVN+ycXw1aBmex45pWUHLyOsVoxD1C3VFtWY116ygZbj96U2rF9oUVRtwWFbQMh5ySnGOtaBleH4u4OQOWoanccPOCRO0DKlX3M67Zi90n+hdkwrBFZtFUc0foBFOU1TPBQ39GrQMqVdcz7ziF1oVvXJI2NamqPqEUJ4saBnueQ4J0aHo9cYlRitoGVKvmHlE/FnrRO+cUroOQcvw9M5po58VtAypV9x0HQhahnuqESEQZMsVvfQBtHVVRXUvoJcRtAzP44b0ioOW4Q/vnPJnDUXVJzR21jzR5FzAn7UU1XWA3lvQMrymPiHNJWgZD/WK+bOCliH1inEuQCTKgpYh9YqZU4oeCFqG1CtmXjHb2hQVG/ishLsrqnvBpwFhtFqaQzKxZAQtI69XPKG/WtAyJLccd80mJnfQMjzVB6gRedAypF4x84oNqCl63TXjV/1Eb58QRuhBy5Dccp4LKtCmqN4vgBF60DI8r0kFy/IyFNVzweTPmopedUoL0DBaeW55JboV1bgh4jAetAx/qElF1E70vm/Y0YCgZUhuudSofKFVUdWI4Gd50DJCbnnMI9pEu6KqDyCPyIOW4T21AZpL0DIkt7yeueUvdCl65ZAsoFtRvWcEL8ODliE5pVwH0K9By5B6xVgHcNrwoGVITmk7a9W+yHqiSZ1SNqApet0z4s/qil71imGEQcuQnFKpU/pCp6J6xwRqjgctQ3JKedeMX90nevuEE22tRVHNIfmgpqjePedKGLSMUK/4qEXDr1ZFtQ4JnFIPWobn75zi0O9By3ioVwy53oOW4TvNIfl8dSp6rQOwrKBlSL1i5pKxs7aiEjNCKcOXuRZFNV7AlTBoGb7TmlSIw3hzRWUd6NwNW1VU/AGUDX+hn9GqeU0qZPx40DJqXpPK+NWh6FWTCv0atAypV8z8AcytoGXUkr5hAY3Ig5Yh9Yrl3vFrxSgneueSIbjiQcuo+Z1TSAketAypV8y752xAPdHkjgl+Vm+Kauy48atdUdUJPw0Yf/P/AQ=="
						}), BinaryEncoding.Base64), Compression.Deflate), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date},{"LineID", type text},{"ShiftID", type text},{"MachineID", type text},{"ProductID", type text},{"TargetUnits", Int64.Type},{"ActualUnits", Int64.Type},{"ProductionID", type text}}, "en-US")
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

