table Fact_Quality
	lineageTag: 7dab234e-166c-5160-81df-65603ff0cab0

	column QualityID
		dataType: string
		isHidden
		lineageTag: 0485b2b7-ea52-5c6c-b55b-ec27d03a6ca1
		summarizeBy: none
		sourceColumn: QualityID

		annotation SummarizationSetBy = Automatic

	column ProductionID
		dataType: string
		isHidden
		lineageTag: f7f23d4b-d697-5236-8a8c-a36e5ffe4160
		summarizeBy: none
		sourceColumn: ProductionID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: dd.MM.yyyy
		lineageTag: f75280e0-bf74-541a-b6c5-553cec31c82f
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LineID
		dataType: string
		isHidden
		lineageTag: 69b9b649-8ad6-51b7-9d28-fae20dedbb21
		summarizeBy: none
		sourceColumn: LineID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		isHidden
		lineageTag: 46db6c87-0510-528a-9c09-2df4419fbdbf
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column ShiftID
		dataType: string
		isHidden
		lineageTag: 3396ac13-21be-5a18-91c8-7e00fdcdf4a5
		summarizeBy: none
		sourceColumn: ShiftID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		isHidden
		lineageTag: e5fede61-0de7-54b7-8d49-80acf2c7f21e
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column InspectedUnits
		dataType: int64
		formatString: #,0
		lineageTag: 03762a6f-3f20-5ec6-b9c9-37680a1b9e72
		summarizeBy: none
		sourceColumn: InspectedUnits

		annotation SummarizationSetBy = Automatic

	column ScrapUnits
		dataType: int64
		formatString: #,0
		lineageTag: 460b7398-df62-542c-b52a-24600c1acd55
		summarizeBy: none
		sourceColumn: ScrapUnits

		annotation SummarizationSetBy = Automatic

	column ReworkUnits
		dataType: int64
		formatString: #,0
		lineageTag: 62875799-74c8-53f9-b815-4582e30c9ef6
		summarizeBy: none
		sourceColumn: ReworkUnits

		annotation SummarizationSetBy = Automatic

	column PrimaryDefect
		dataType: string
		lineageTag: 4609b909-c7ae-546c-9aec-844807d99484
		summarizeBy: none
		sourceColumn: PrimaryDefect

		annotation SummarizationSetBy = Automatic

	partition Fact_Quality = m
		mode: import
		source =
				let
					Source = Csv.Document(Binary.Decompress(Binary.FromText(Text.Combine({
							"hL3dDiY5bqZ5vlcxF5AGRFKipMMFOg8GGCc8Ywz2uNcuYxprtwfVbSx89xN/bwQjSKobaCALWXpLXwQVkvjw57//xx//9U9//c//+ocf//D7v//zf/zTX//073/e/uEPf/zrbz/+25/+/Nv257//4z/9r/NP//i//vQvf33+1e1P//XPf/nfv/3TX3/75//55z/99S8//vGffv/j/z7/+D9++////ff/7/zzP/z+p3/74+//+Yff/mX7d/+v/172/9GPf/gf1x+4sP5dob8r/OO/bf/499v/t/8G1fJjFPnB/IPKj//nt3/95//yz1aAIcCRwM9NoGwCbf5g/UHy4w9/+rff/vyX7df98V//y2+///7vv18yAhnxMvzj1yYj5Ucn3jX0x//9l7/89m//77/+50uiQqK+JXiTqMdPKbvE+EF9/yl/vz3b3/+0TeP1cxpEWiSy/5xtqOr8sU1lpL9GoaKRyvVrdGx/Sz9mqtKh0t8qsqno8YN4U9nmsz2TnqoMqAyv0o5ftKk0bj+oLn7RhMqM5vLrtJM6tr9t+/ONXtA20VNj+8NLo24a/fg9+zvm46lsj9fZGsFYiSKBn+cktG9GMnaBf/yP3//lj//021sD9krsNcb9aurcnmjLngbBWslYa3utmt3o9bD4ET8MWCtVL8HHb9nmMa6HUdKZwF6pRTO53suo/XgkEk8F1kr61ngWzjaBvv3j/FFjBVgq9UjhJ5beNgvdRML3AjOlEUn8uoy96m5dM168BCOl+dZ4Fsz2TFvl3dS3nxTNg2GkXLxGg401xQMNJ8IwVKZI5Nf5RGvfnpb82N5cOBEYKvNb41ktu7FPOTQ4mQgMlcWLjPtzNo81u62qWASmyjUS+XW+Xe3jMNXq1y3DSNkYqd62fr2XobQ/0NzWGXbK6mXoXjKN9ke6/Rg/D5gp92gel431NnaBHr8VmCmPt8RupvJsMmWfQCIBK+UZSVw/o2s93knyYgVmKsWLPMtljuVXXWCnQm+V94LZjX1ui849UIGNCvvxz97Sj6ND+jUVGKlINIvLvlqVfcnFX1OBiUp9S5wmik/Yvux5m0j8SGGl0iIN7C5Tr7XinwbsUzQSwDrZvxtzF8geB6xUjJX21+aC1bIfQSITE1ipDC/xbC7lWCnJx1RgpjKjaWCx7I9Df8QbfoWR1vKWeC+WdpiHZs+jwkgrRSrX5qKznKYePY8KO63sJZ7Vcr7X+HRZYaRV3hKvw1jb3wplFlZhpbV6jYbXciw3ST4eFUZaWyRx7SxtN53jaxpqwE6rvjWexXKctWV/s9uvCR8HjLT2SAMvZVsJ20tJT7gVdlqHV+k4veh+5qR0e6ow1GoMdbzWy/ZIxjb8+HyEGg2W2kqkgQXTjwNMdndoMNRGXuTZXubcn0n3348GK238Hv9eLoyNIXq3DWbaJNL4iX1h/xwHJ+wGC23VD6+3ee2LvmUnqAYTbe2t8ayU/XM+5DhOJpbRYKNNvcizVArOHOFEYKOtRxO53kcrx+cnvT812Ggbb5XnHLa/VTl2/HSnbTDSNr3KeH3EKP8UKsxUS6SCHUavW3L0UBRGqsZI5+sstknM7Zcd5+xQAnaq7CUINjbLcS9N177CUlUilWvt982O8wO/wly1vjWeFbO/2uOgtb0bZ+4KU9UWjce9ZZsHzfBGqjBT1Ujg3lh0Hx1vLAor1f6WOC0dy2U/ou9PM5SAierwEnov+vOeED0GGKfOaApYKDJOs3LjO8yyl/f41+lLWzuvw4lBdFhmp0gFv2KU47sRGWaHYXb2Cv1eHtvWeewE/nfAJPtjksTftTE6LZ0/HUbZq1e5PWJ9HIev+LzSYZe9RRLXZ7hv38b9sxMv9A7T7PrWeG71ch2+KHypsMve/fhnbZDml6UOu+wjmsL1M3Tb/E9/jZ8DDLPPt8CzNnbDPG98Gn8jBoxzlEgDx/r9brtyUA5Y5yAvo/fOWMfSNgYsdPBb5X1P6dehOv5BsNIhkcbPx11zejmiL8aAjY7qNcxKKaeNZr8GZjqMmcprveyf8IFHG84EZjrUazwnr/2ntOjQNGCmo0fjsY1sm8wmkW6sA5Y6xlvlvZFs19zD0DIVmOuYkQpu9tuTPQ/nicyExc7iZer9crb/SLojTFjrpLfEs3D2lbc/Vc3f74S1TvYqCktrpZ/7QmitE9Y6JZrJ9X7accxbXIonDHbWt8yzcI6v0fVpDp8JrHW2SOL6EPTjbrarhBqw1qleo99ftP1vJbt+TVjsNBZbX/eV/bSy77b5XWPCYOfwInxjFzoce/kLhsHOGU3lsrQhtLrF7f/KobL/4aXyBi9K+aWBwKHIcCijcS+duvogEWAUGRh1q8jjgenxnkegUGQo1DH+WTa4oJf07kIAUWRA1K2ieDft/KSFh0IChiKDoYwEdpsdL81988xmopDRt8z7pr8ddw6nRfhiOiR6JIHdptXLWZDNZEBmeJlnw5F6GX0mMyFjDLa5E9p2ydoO7OljAYgiA6LozV72FXh+BgIzAYciw6GofV1jY3d7anDOJDAoMgyK3sAFnkZOL6YECEUGQlH7Lhmt184ZmRkgFBkIRc3tNGvaSWBQZBgUNbdq2n49lngesFNDoKh9/ch1tNTFR0BQZBAUNQ8odbn3EjAUGQxF7XvbH6TncSKcCWyUZiSB97L79yX5MYBQxCWSwIVs0vJrCApFhkKRxy50XfWjFwMIRQZCGYnrUzb3C7Zkn3YwKDIMitQ5ks+zZo8lYKeGQNGbuhyHvG0axx3VrTgQKDIEivQLKHW0FUonACgyAIr0u1x6GfH9ksCfyPAnUu8ZOzzZLZ0FTNQgKKOC7WXn8C25QxAYFBkGRfo6lUFDko0BBIoMgSJ1fjE+UEeNJWCgQl7i2Vt2TxUF+ImAn0g4Gg/vy5gn9YkMHOyJDHsi5w4bJAsYR6BPZOgTvR1iuwe6jBSVEOATGfhk5oEthcf5U/yjgGka9kTOE3YcTI8tNpwDzNOAp1vj",
							"ofhlnB8uPwcYpqFONN3pazv2nnw2fpawTIOdaPo1oolLjgCdyEAnejvD9gtHPy8c6SEO1IkMdaL5vbfU/R6vEfQmMCcyzImmO3tJPS9P2TRgn1UilfvDtbzIEcAT1epV+hNckfuNCeCJDHjaxtiFsq/VerGryL7Anchwp1viWSbH80ocFwTuRIY7GQ1sJqrniSU0MVAnMtTp0HjHu2jJ2QIBOpGBTkYDgRVNl28X2IkMdrpV5L5ObsdZ/RFeJgnMiQxzOhReF/22e/kWzJmAnsigp1vmXjS6X6taggQJ6IkMejIauLPcQS/ZVGCrBkEdMs+6qddtcnXhAIWi1rzMHSt2YJue7/jAUNQ0mgyixfaIkZLsk6BQZCjUZldfPHk4BPM7NigUGQp1qzB+zti/3Ef0SviCYLOGQRkNxFg2PaO0wrUDAkWGQB0ab6/y5dL1QRIE/kSGPxkBvBfq554fPVHwJzL8yUiAGu8Xn7k46gNAkQFQh8zbuVzHCg8SEBQZBHWr6MP0y3nF9s8DdmoQlJnFHSo2z6O+Hw8LNQTqGP8cw44rXF+F4BAgFGmPVH4+4UQ5syVgKNIRiWCX0XZOJTJRkCgyJIrZXVl2kqRRODIBRZFBUcxfNjl2zjoWXw+wKDIsit/hyAcY5OM4FbxWoCgyKIpdMPLxWsLzHFAUGRTF7zhkPunLTDZsYCgyGIr5tbfsny7p56E0exAwT0Oi+B2DfGwMGcIhYCgyGMoIwIfcxnWei6wCKIoMimLHXurka8GHXy7AKDIwitl5kJlP15H/ITDNPqPxeCPSz/HR7wCKolG8RH92k7JcqyBRZEgUyzc+rM+x3NlAosiQKBZ3GJOZh6gSSBQZEsVv9nKEmZ07frrYAKPIwCgWHyZ2eaHDmcBMDYlice7j3s87cTYR2KphUWYicLtsC+q40oavGKZqcBSLu77Uef4WZ2UAUWRAFIu/vcw8BoiAochgKKNx/Yza+YxRTR4GKBQZCsXy2lj2s+n26lN7B4WiSV5iPE79hVsPCIomR7MAPppHbGjswwKBIkOgWL+U8oi01+y4D/xEBj+xuuNXxb4UasBGDX9i/a6WLu3cErLXAhs1BIr16zveY5g5D74hMCgyDIrfMchHvCxWf/hcYaoGQbG6JJfd1PPoTgKCIoOgWF+nsOMF9xNkBQ+WwZ/Y8Cf2DjFdnwcZCIoNgmLvE9t9/jVHFAwGxYZBsX7vL0cQSuKWZ2AoLuIlnjwXmad3LtruGBCKS42mgUMyj3PhhM+1QcIYbPeHMY6Ppgz6xIY+cXepYTpO30U4hQ6JHkngHMa6vAwy6BMb+sTd3VroIur+l0yMn368PKHhI/WfMJgTG+bE3a0WKWdwaPJDQJ7YkCfu7rq/u7548TwAoNgAKO5ul9HLwCIbBX1iQ5+MxPVmjk0m2R4Y9IkNfeLuri59ni4l91bAnZhaNP7nk2WXcVYGeGLSSOIOtaAs5ozBndhwJx6vRXIE/V4JIeEkYJ2GObEPPt6/OjWzLhioYU5GAutkv1Vx4r9hQCc20ImHc4ud2XXZzsKATmygk1HBS8EuF04E1mmgE4/XMaxeseVJPgiDObFhTjzc3b6P85GGX1BAJzbQicc3qrKdAaqxu5LBndhwJx4utUX7CuQxuBMb7sTjexTr51Ydf0iBnpi7l7iPYgrfj1trgE7MIxp/e5Dr+QUNpwAbNcyJp1spZxZY+iyAndhgJ6Py01wWSnCxZjAnNsyJp3Mgy+VviV4qsBMb7MRv1sKn/3jEtwQGdWJDnXj6aBc6bvfZk4B9GupkRH49Ky37dgE6sYFOPB2432+IRy6If5gwTEOdjMCd/0VpfAkDOrGBTjyjSJdzlWUPA/Zp2BN72rJ//fJLMQM+sUyv8hy8xjh/T6ICAsW1RHO518oy1p8BoNgAKCnu2rK7tyM4yuBPbPiTGX97jOnYEmI7BX1iQ5+kuDhk5AdmvwSGauiTFHe/P7eEeJ8GfWJDn4wEFgwf18DAL8hgT2zYkxS/p8j64AT8xAY/icctRzxF8PEBeWJDnszwbwJYNglYqWFP4kBL1ZamcDDAExvwJCVKLj5D9sINEuyJG0UidyDyMlyegZ64caRyO8XmmavonimwE9/Yib8VLI6QMLk8vuHjgIXezIlt9Ql4jc+rbI8lYKE3b+JvAYvdyPeQnRmBEQZq4hs18bd8RT3Tgs+DYDgJmOfNmozGc0/RRbw8gzTxTZr4W7viiAKQpY2CNfHNmvhbu4LOxJgzys49DoAmvkHTSwBLZXLqFGSgJr5RE9vKF3DnnXtCYFngTHxzJv7Wq0Cu98K+gZlYxas8BL+P47QQvhIwJtYaTcRm5WUXaWAmVmOe8j18jTlybs5ATazqNW6Xce/t4ubZA4GRao+mAj8Yt+xbDs7EOt4Cz34iV6GXPHySgZpYp1cxIWEzrTjDgE3cSyRhs7+SmAgGaOJOb4kXX2mzLCRgpp0jiXtTkWWEPYM4cRcv86wWnedqyVRgqr2+Vd5RYWfNmsBnBN7EvUXj77iKPGKZQZy4aySBoIorDT91BwI6cTdmWn2Nl3Js9eGCAXLiPiKJ2wFWEwcHkBP36cfzk9vSjihwzn4JsBOP8pZ5J7fs33tO0nQY0IkHeY1ntbSS8UgGcOLB0Sywz59UInYMgDfxkLfEe7HsGCnzWjNgE48aaeDKMnffrI/qYoAmHi0aDh5BsowuY5AmHvqWeZ+/BHnWmQxsdPRI5vZL8nk+D58HbHQML/FEuOw/V8NzC2gTD2Ok7esl7hMXOCcA0MSzeAG6Lyqdlz4SsCaeFE0Du8q+lXMCzhiwiSe/NV4XFW2U5zsxaBNP8Ro3uD/MnJMPOmATzxpJYFvpVzGT8JfATGd7S7z9X2XEiTAMysRT/XgTYywnCc3eCcxz9kjFFA2TI/g7fqAw0DneIq+lst8e46phDMLEc0YC73zJzL4EkElKiVTuVAk6/ffBexUAJinGRF08fh8zKTAjQEtSOBLA",
							"LfhMk9BgvGC8+PFPuleh61EGliXgSlLqW+Nz+Cop3hJwJSktkrhPXiOtniZAS1I0krg3E0rC0ARgSUp/C7zLucy83qAAKkkZkQTOXZUWxUsEZEnK9CLtVVevJ1uaAC0JlbfGO2Jy9mUpOQFbEqJI5s6/T0OOBFhJiL3Cc/KqqKIS/hjYKBkbdQH5fS4P9wK0JFS9yoNUTi+vpiowVGrRXHD+2j7TckSjZjIwVtK3zHOzP1zO+90t/ggKKJNQ9xKmrMsVmRJrwF5pRBr3LbJmawaQSWi+Bd6bilIa3ydgTMIlkkA0WK0n2kkeKBiTMEUqcICNeh57IlMFYxLmt8Snqss8fZLZRGCsLF7FpOLX5CorYEzCNRK4Q1n54tvhiwVkEn7MlFxo/qCS14QSICZh9RpPONi+nDKAKGBMwj2aB37MPEvBcvpQYac83jIfWF9WcSUC2iQ8IxXslcIp5xGgJpESSeBzJpJst0BNIvQe/6rsooXiWDABZxLhaLwt65K4fQSgSUS8hGKfbPuTzkp9CTiTSH1rPNsLuN1iqYA1ibRIBe9j3xsSyC2gTSLqJd5FK2qS+CbATSLGRukbPDnlzJOK1wpYk8jwGo+3mEp6kxWAJpEZTePm9eO08WgWoExSy1viHWHcyrGrRJMAYZJKXuEOAtuDH9LCaQLKJJWjWeCuIhxH1ggIk1R5j3/5iY9sLU0olYAvSa2RBi4rjdIQDAFfktoiiV/mvsPZ+4B1Vn1LvOMl51zMAsZZeySB7eQsx5DujoBMUkek8sscr1u4KYEvSTXG6YkK1byMrgAwSSuRxr1G5uE9CxVgnY0ihV/Gk5izRwFdksZvlXfmMF9R2+FEYKIGMH0KIR2bfD/fSvRiwZfE8KVPISQ+S+KlXEYAmMQApk8tJGR6ZeEoAsYkhjH5Wkg7f1wlyQswkxjMRA6s1DM9PTZ1UCYxlIk8W2m6CoUXUCZpM1JBMMiZgxwvW3Am0RJJ3MWN6/qRgDWJYU0k3zUziyytFcRJDHEiT1i4p2nZAtwkBjd96iEdicQzL8Yi4E1ieBO5gHxVXZ7AgJzEICfyMfl1rErUCKCTGOj0KYZ0+Cd7ssGANomhTb4SUmtXAm1kq+BNYnjTpwzSEQhW0ng0AWwSA5tInNt4yOWdjDRAm8TQpk8JpHp5fzJjB22STpHE/UpQOix5JyBO0tnLPPf85cEBuEkMbvoUp9g3mdnP9xJrwE4NbPpUpzgSimUZHSxgTmKYE6lD9+NKFY2nAjM10In0e2k5Nl3N1z+Ykxjm9ClTcRDWcd0nw3cMazXQidSVpOwtJnAC6CQGOkVFKjit5S8ATmKAE73Lgh+nqZpcnACbxMAmck6xvTrFKhJfQJzEECdSl/ElLY55FOAmGRKNR8ZXP4N9sknARkeNRHAp3r/WR13fTAY2argT+aLgtSZvFcBJDHCi7uuFcX6IAWwSA5uou2AwakvfDXiTGN5E3YW51HGtWf9LYJ+GN1H3rrBx3Hsi8wRwEgOcqLv84TnOyLroWYA2iaFN1F3h/K5pGwABbBIDm6i7xEiaeRkXAWwSA5uoh9f7mnmPQZvE0CbqritLX8b7CICTzBap4K00Tp3HQE4y1SuY2saXazCUgIUa3kTDVdZrmsYMCWiTGNpE4xs12QdfjCZ8orBQA5xouEQv9DOIn2gFcKoGONFwN5ebe2UyBBnyMg+47z09NVRgp2qwEw1f5HgZz1oBn6qBTzQcvN/hQ8vLQ1Twp2r4Ew0XclyTEn8V8Kka+ETDLZn9Et+SJVNBn6qhTzScR0z6KpenAkHV0iMVwPt61LKLL3QVDKqWEWngdMy8jJ6uoFDVUChTwAheMarLrPkKEFUNiPrUQaoXu0kYaQWEqgZCfeogXc1RmDNkXMGhquFQNF0mC9cLiDkjAYSqBkLRdOHGxOnnvYJAVUOgyFcGH3kxhAr8VA1++pRCuoqynC83nAZM1bAnmu4odvqwZzwN2KlhT+RoSzsmmdxdKthTNeyJprvun03I0hUDAFVpRip31iqtzRQQqnLxMuO+vnQ9z/vR7wGBqoZAsQ/O53HVgQ01YKUGQflySHtwfVqyqwJAVQOgfDmkPQBo5F9mQKhqIBQXXzssR/oVCKoaBMXFH8ryenIVBKoaAvWphSRnxYyjTo5bs6BP1dAnU34I95bCq64EFfCpGvjExQFKQQ2z8JfATA16Mhq4vhTK29RVsKdq2BO7AP0jYzXJe6/AT1Uokrj3l5KEYFfwpyocCeBEVpblCisQVDUIisXH51N8GazAT9XgJxYX9NJGCo4q2FM17InFXfC1LKrbVNCnauhTUKXirOww4jcCEzXwieW7SnqbxyHZPwnYpuFOLL6c/oUH/HjYpYFOn9oUaPOQHQUBnaqBTixhAssibrGCPFVDnti7w/q5pUg8FVinIU+f+hT1cnRmvpIK+lSrRBp3t896vJDolYI91Vq9wnNrOdO643UK9lQNe+LqC4S1qwVr9kxhn4Y/cXVhlFcKsE9OqqBP1dAnrq4EpdS/8W5hpQY/sY82nvAxhic4IKhqEJQRuQNbr/LmoQYQVDUIin3AsY712RgcqhoOxdWnEtc0Wq0CQlUDoYyEdSC3xEgAoaqBUEbil6kpnkfnV3CoajgUVx9LWa+dKZOBxbbmZUwl/XkFQYc/CObaNJrK7aakNCmwAkNVg6HYFwPfcWmSB1eBoarBUOxjj/evXcsjvCo4VDUcin3w8Rgr+lOBoqpBUdxcnJjWVb5RBYmqhkRx8xf+mkYnVGCoajAUt2+y5B7ZeGZQuE8JIFQ1EIpd+HFtyxCeCgxVDYbi5qpUtLV7v4JDVcOhuPlKFUmHkQoCVQ2B4uYcZAqPZWRnoFBVe6Rx16dCo6nsp8BcdXiZ5+bSes6AK1BUNSjKlCH6w1O0q//IcGcFi6qGRQX1kGjkPKsCRlUDo9hjl3ZFekaPFSCqGhD1KYa0S3RKnMkVFKoaCsXqqlVMWbxbUKhqKBSrSy1W",
							"PAs/CRio4U+fEkhyBUXGyw3wqRr4xOpOZUMXxymgp2rQ06f60VE0bKRJBxXkqRryxL4Ja53npu1/BiyzTz/+WSQILXfjgZ3qKNF//0b5lJ/FQJ6qIU9ByaOaVyetoE7VUKdP1SM+q7nM5PML7lQNd2IPWq6gvTjat4I7VcOdPiWPrmouGhepqEBO1SAndqDlOCzkxRAqwFM14Mmo3OndLYXnFeCpGvDE3XmOtV4Jjt4wYJiGOXHQd/VqhRY/TxinwU6fekd8xxwnNSgryFM15MlXPLorISSPFPCpTopU7o/WSQZiGwN9qpO9hnEca9wCpYI81Zs8iU13x9mr8PKsAvZUb/Yk37z7fRspBylJ3YJgT/VmT/JNvZer1HNSfr8CPtUbPsk3+f74dNH56QolYKU3fJJv7v1VgT+DTxXwqd7wSb6p9/ViNYtDPvBTvfGTfFPv+SqZmAQiNrCndrMn+Sbf16vgqmQSBAmKJBCj367WnMHjaOBO7eZO8s2/p4eAZee/BvDUingZ08GIrwiv8NdUaNRI4w49vuJDo8XfQJ5aMWYq0d6ywGgN7KkV9SoPYxk9SYdrwE6t9EgAu8v+hTpOPfFvGRAZb5HPVWVRhr8BOrUyIw1bPiQPmWlgTo2KV3lOXyxp/cgG5tSI3hLvEpRjLPOnGqhTI45k7l0Gbt/woYA8NZJI5Jfpe1ziM0wDeWpU3xIvOjnOGg3xJaEBPTVqkcbtdKVV/lQDfGqkXuWJE1NNY+8a4FMjY63eOdaQYZPNBPZKI5K5NxpNspwb0FOjGQncBcGv+hmRmQE7NS5viVfm5L1BRE8D2KkxRRKId0VgZigBK2X2Ek/LrzaWXr4G8NRY3jLvNbNfq1p+oW1AT42rlzF5xnnQfAN6atyimfwyBfjzyl8N9KmxvlU+vIWXYcANEKpx9zLj0zTXH6sa8FPjEU3jRpMjYTYN7KmxsdPmaIvkPb8a0FOT4iVMhT1Oy2o2oKcmFEn8ekDH+TOSpwkA1YTfMu9cY2krpNcAoJpIpPLzebVZYFEDg2pSI4m7JtKZGht+2MGgmrS3xKfOsVzNb7IfAzsVjWR+mrzl3LPWAKKa9EgF3mRJgqobSFST8R7/vuk3OR3a4SOFocqMJPBW9pW/aAjZAKRaLZHMnX9U0pCTBhjVqjFWVx98ysnyw8JbDTCqVfYaz6msz9VFpgFHtSrRTH49Ed7n2S40NBCpVutb5M0pJ62qvzdAqVZbpHJnVozkQwYa1apG4+8kpH5+lf14WGjt7/HvAEtdHw7BolodXuU5krV2LTo/DVhpnZEAFkrvaTB0A4ZqrbwlPsyFkicJ/tQa+fFPWn7XLM+vAT+1xtEM7svL9UEPfwQssxnLnN8U40kon+h/BayyVS/wygdLz0+gTq21aA5366+rG7WfAkyy6Xv8O8xFrui0cAqwyta9xOMuHnSE24QKsMg2IoV7XeSlfBtgU2vzLfFKKz68WTM0anCmpiUSQIzL2ZEq350BmpqSl3lyJmvNUvwaOFNTfiu8k/A3se2NxwqwS5VIAd/dIrHLuAExNa1+/B2dv7c8TFPnG/hS08cuTer8HUB9lTEPJWCaqpHET8MPM67TgJiadq/xLI8yY49eA1tqOt7jX4etPUOAj9SP8HfANHV6DcMe6XRxRD8DZKn1Ek0DG3qRlWOxgS21Tm+VN7RvV361exgAS61zNB7oUTQtrNWAllqXSMIWqeiLHwID7fWt8umyqmk59Qa81HqLJLCBSF0eGcGYWlev8njAiPPaLg2MqXVjovQ9aR2up/x8A8rU+ohEkMkiunSjgTW1Pr2K6SMpaZPmBtzURnlLvDNZel4SvQE3tUFe4kktFlnUAW8ATm1wJILLyRkGEQdCNSCnNuSt8ekr0fNvGIBTGzWSwK7CJY1YbCBObTQv8ewoZdnstIE4taFvlXeeJOfhvQ3EqY3uJZ64sH4WCczmAUMdI5oH7vK7fyTpkNEAndowVspf79cslOcINTCnNkukcaP6q/J/NA0ApzbJS/CTmrNMAGlATm3yW+Xt/9KaVmRpoE7NUCeK6xsvIkIasFMz2InYE/tlp4sG7NQMdvok5NfzKs49jx1qQE/NoKdPTj6fOVyLNpQN9KkZ+vRJyT9CdvjELZkKTNYAKGK3dNo6vLOBQLU5I5m7jL6sLm8KCKWlRCp32tFYeX8UHEoNhyJxxZG45v0HFSBKDYj6pOWXy90RuUsUBEoNgfrk5JenpW2J51ChUd8arjx4tnoUAEoNgCIHXPYLUNIwQgGf1MAnEp8J1la+BQWBUkOgyPOW1q6AmUxmQGZ4mTuBsuJuHj6RCYkZzQRQv7VVF2cFglKDoMjXPD7CuuNoDQWCUqJI4q69V4+grOingD4psVd4dpsyk1JkCvKkhjyRugoWoivko4BPauBTkJKvV/Z5/DBgpwY+ffLx+YotyHogKtCTGvT0ycdHKZ3FxwP0SQ19+uTj1ztItcfvBVZqyBP5SpXntzA+nSngkxr49EnJPxhnPfer8KGCPqmhT5+cfBPTmW2dCgKlhkCZqdxHtLJq4qOAUGog1CczX86Lf1bZTAGglMVLPKVfKPU+KNiTco0U7rt/ufwo2W+BtRr+9MnMv+qEHy/HrTuQJzXk6ZOZT4+159OAqRryZGR+PREsnNxGFPBJDXwymfX3mlnWRFQQKDUE6pOfL9fhKr9uKiCUGghF3bViVT5O4NGvAYNSw6Coe6pPPySLklIAKDUA6pOjX85q34edZb8FpmoA1CdLf4+m6ZLWoFIAKDUA6pOkjy+ABn4uBX1SadF4xPKVpBK9AjupqB8/nqzpvtz4gZ3UYCefn99rWZsGzNTAp0+K/uEsk2t7CD+HwE9q8NMnR5+uk+6MQKsCPKkBTzT87V+WWTsK+KQGPn3S8/lMae2xe0eBntSgp092/r7eaK6/H2BPatjTJz1friaqUZqeAjupwU40fBcKpJaEPwVWaqDTJzefL69by5cb0JMa9PTJ",
							"zke7g0XYmIJAae2RzL3B0PJsCAKldXgVk0PJKXRQMCg1DOqTnL9f4A/oEH8KgaDUIKhPXv5+tKMrhTL5KQBRakAUuWrIYz9KU1IaQ4Gi1KAo8q3zRPMDFVCUGhT1yc0vV2HXvK+9gkep4VGf9Px6lfpfHYfApNQwqU+Kflk0r1IwKTVMyoy/043nsqWOgkup4VKfFH2Ur0wSzBRgSg2Youmu/tqWUEgBp7RNL/MAGdZlfwwFolIt0Wx+PfehLDdEgafU4Cn2VZF5XJVcspnAYg2j4uKiYc6ordTcwKnUcCp2jfT2FHuu2dcRrEoNq+LirjSUd8RSoCo1qOqTpn+Ya82LAypYlRpWFeTpT+SZZk8EJmtwFRd3PNtNNiI0ClylBlexJzRarqSA8InCWA2uYl8deb8QzySPUcGr1PAq9oCm6vKiCV6lnSKVm2PqYvcEs9LOXuNZM/N4s/FGAWalhll9cvWPgnqcF+VTECs1xIqds2xwyc0UxEoNsWLfIezqTu+jDRSwSg2s+uTqV5vWlb0V2KjhVZ98/fIcEtOPGYiVGmIV5O33ZZaDglipIVaf7H06Ky2fdfXcQwGvUsOrWFw65X5+O+oLhm8XxEoNsWJxVLMjoiZ6vQBWaoDVJ3P/OFlJTKoVsEqHRONNR70saFQBq3TUSOLOtBjruz+AlRpgZVLmsV6uzKTYsQtcpQZXGQ20qqBl/KqCWKkhVuxbhR3uxYWpglmpYVaf5P1iKjjFJgJDNdDqk7t/dEQ/3aHu7YJXqeFVXL+rpZ+VdBPvH4CVGmAV5exf1Dx5GABWaoAVV3c465RWHlEAKzXAin1w8l2NN5sJzNUAK5Nwb1uzzyRNVYGrdLZI46fJPVt47kCrdGqkcoePt7CEiQJTqcFUn5R95I1QZl+AVGogFTdXfr/U9Q+BlRpGZTL/fz1REYmDqYNPdcOnonT9nm50HXCqGzjFrlnYUVo8KRLWwaa6YVPcvvWRj+5WCRfqwFPd4CmTIH/H8mtuXR14qhs8xc0dx/Y1fdzeQ40GjRbNA4n6s6Ze4Q5A1Q2g4uYcyzKXn8EOQtVLj2R+mhq6kbutA031Mvz4Z3upsgpk6KBT3dApn6k/a+JZ7uBS3XCpIEl/vwssbkAdbKobNsUOx+x5wCMNhujAU93gKVZ38e95gbAOQNUNoGJ1NcZaW3kxOgBVN4DKZPzj+lJmzHI74FQ3cOqTrF9Ot/KB66MvWAec6gZOBfn67equF61ZkKluyBTrN73ySAE7Qqz974CJGi7FLix5DwvhY91njxM2SjOS+WnivCm3dMCpziVSeXc8TF8t2FQ3bIp9jeSzkWT8QQaY6gZMsYMxR4317ALUQaa6IVPcXV0L4usbFM4DVmrYFHsUc/eFikwEYKobMGUqANybS4tv2B1gqhsw9cncL1dt0bp4tTBUw6W4++IWKKgbPg3YqgFTn/z9epVKHlmXrA4u1Q2XMiJ3p722PPJ3gKluwNQnhR/dQJKcxg4y1YUiidvnf30LQwnYqbCXMCUsV7OAmRoqJcXFlu1+6+M6GL0YYKlusJQUX+uCV21CO+BUN3BKyhddHsmZkrseOxhVN4xKXN+w3fWVpQJ1AKpuAJX4MpZdj0NhqABTNXBKivMr7091UVCqA091g6ekuFUjeppIogJG1Q2jkuJv/C3v/tUBqLoBVFJcW/ByXKWC/RJ4qhs8JcUV4e8j5kodXKpX8eOfyBgai/0WbKrXGmnc28tZyN9PAfZpsJSQq3Vx1l4LtloAqW6AlJCL7p8lbVfYAaO6gVFmCvf1vvw4vm6pQcA6DY0S+vrFRhmXYy00CJimwVFC7npf5+lmTGYCJNUNkhJyx7CzqFa6uQBJdYOkxIct95ne0DuIVDdESsgTmJ46kzqIVDdEyszizqZEX9/QRgGkugFS4qOWSfL+1R00qrfmNUw78GUWYgeT6k2jmdzpYm1ZJLCDSfWbSdW/K+RSxoosuXQHl+o3l3rJ3I0raBV73IGl+o2lXipYP9s3Rjjx9HcwqX4zqUvjzV/OH5Q+XWCpfmOpl8pPUxOhLVRgtTeVeqn8Mv1gJfsqgkn1m0ldGm/iP5L2lh08qt886jUeK0fnGdaS/RLY7I2kXip3mgyvQmw6oFS/odSl8q7IX0sW2trBo7r2SOGnOe0uPHUdWKrriGTuLKyxSl/qAFNdjbl2x2F45J4QcKneSyRhqt6kfiFAqd4pkkC7cGqLSwigVO/81njf+/f/Jy8GTKp38QpPzmWreQ5EB5PqvUazwKlMRn4zBJPqvb0lPlWVWkz6O5BU7+rHP+kxmsYrdtCo3nukcG2ZR9e9PKq+A0b1Pt4qb165rbftUQU/A5bZZzT8JsiUViDp4FB9lEjil6niz9FxDAiqD2OWw9Xer20VqNwBofrgSAVhl1KXrdA6WFQf4mXejVzTsnAdNKqP+hZ5e5KPkpzpYR8sqo/mReRVkjMpuNWBovrQSOIuoLhfOSSdB8x09LfIe1uZbdXAvQNE9TG8yrNczh4N6XcUKKqPGc3lbiRWV3V5O4hUn+Wt8u7selbLiJ8sgFSf5CWeahdnXZjc2kCk+uRoJnesX13lCnVAqT6NzbpuL6PVy0HlViBwVJ81EgCy1HlWhvTjYaqzReMRSUblPKeGawYgqk99a7y7hHM7H4WfA8x0dj/+afHCNfEDg0L1OaLx9ym5rmIVOyhUn/Ot8gaVfD3JwLQGMNQoxUs83SnrjBsiDTCoUSgab4Jg8hb0AxRqFH6LvAEllWU1lwESNYp4macCLPOqc9YAixqlRpO5X82Me+UNcKhRHvOMEvrb3/gxChmNZPBBlnKVyApfbodGjzRA91hXN7oBHDXKeKu8r/1UrijD+BVPiEwvUp8UpZKj2wEiNahEE7kLwl2RMNETAY0aRG+Jd8PwpnnbhwEYNYi9xuNPLpoW4RiAUYMkksCqOfsqZXv2AIwaVN8qr9LihxeEFyqwV2pexWwuIz+nDyCpQRrN5K4s",
							"Xi4Xe6gBYyVjrPKF+0ePyRK7Ugao1KDhJZ5bS29XQ0O3dsGjBs1oDjYZXmKP0ACMGlzeEu/GeyTL7qMDNGowRTJ3HszMS4sP4KjB7DWegrCVTkPNZgJbZXmrfJL7x2qrGkBSg2ukYqFlVMdoAEcNbn78Qyz3G1rLG6EOUKnB+pZ5l1M6Q53jkKsBJjW4Rxo/zbLLW14OUKnBw6uMJ0WJshvdAJIabIy1+oMYQmkjDfCoISXSwC4zJW9YOQCkhlCkgRuZXg1Rk+cBJjWE3yrv2LFx1eIJfwwsVSSSuBPH9Vh6lM4EpirVyzwBly2LHx0gUkPaW+C1Yo4cV8mrQQ4QqSEayeCyvC5vPQClhvRIBZcYatdDCd8wbFXGW+MVcjnOtE1NZwJ7lelVnrAY9DRMVEClRi3RXO6M2JKyywEoNaox2OYbvZa85MkAmBqVI427GRcfl+5QAdZaJVK485TbIhFtgE2NWt8i7xqXfIUKOVMFnBq1ReMR1lda5mAbwFOjqleor9DRmvv7BxDVqP0t8773n/71eOcFnhp1RBJ3NdieR58O4KlRp9d4ulVyW0aADfCp0cpb5tP0RRbHTNCp0SjSuKvIJCl1A2hqNI7G4zMm9fq0ewEYaDMGGgSQycV/wx8B+2zVazz5L6PETT0GmNRoLRpvbjBnnmS03EGkRtO3xrvNC9XY3zCAooZBUeQjx3QuD+sgUcOQKFK3qzDlYZIDHGoYDkW+rGW7aEdo4eBQw3Ao8tFjZyv49FsODjUMh/ok8vMVDpOU+B+AUMNAqE8WP3plj8g0AKCGSjTeBvRJ7EseYFBDayRh+x9HqQQD9GkY+kTdXVl0njta9EqBnoZBT+T6vRwhY5Q9SNinYU+f3H14Cnhx3AB7GoY9Uf8ukyMoKPe8DrCnYdjTJ38f5Z+TbhoD7GkY9mQmAjqpZ6GZUAHWadATdbdOuiwmAes05Im6bxS+s8mwsOMAeRqGPJGLGLsqmiWfLpCnYcjTJ3H/+Pwts4gH4NPoLVK5/WJ92fh4gEGNrpHM3YunpPBmAEINA6E+WZV8wZf9Uxx+wICghkFQXHyb8LNwVmIgsFLDodjFjF2VwJKjAkDUMCDK9z3utCxqMICjhsFRHPjFWmrsQFHDoCj2MWPtqrsRmSow1DAYin28WM9b4AxAqGEglE+oPJu1pU5CQKhhIBT7aDGRvNPSAIUahkJ9MiqPY1NZZiIPcKgxeiRzp1Tm1GYAQo0xvMRdHfa4v2W1ewYQ1DAIismhfM0L8g/wp2H4E5OLsqxXLe7woQJADQOgmHyHSrpKb4bzgJ0a+sTkkMtVaDLRgKEa9sSu4qWuud4AgBoGQLEreXk5cIKTBwDUMACKyXdCTnu0DeCnYfAT0/cQtreTWvnUAKGGgVDsIseuPkv504CZGhTF5PIptaXFOwc41JjTSzw9kmjEdZQnINQsJZrCXdZ6po79CQ41DYdidmUuJLktTSCoaRAUs8ujZM39rRP8aRr+xOxSXUbLK49N0Kdp6BOzcx/3mdZAngBQ0wAo5uhOf0T/Rgt+gj5NQ5/Y9xKrkhS4mUBP06An5m9piwO0pFGNE+RpGvLE7KrCdEqbpk9wp2m4E7Or0TflpArRKwF2mgY7MX+jw45s35J8QCe40ySKNO6g/WVg1wR5msSRyl0HYqRFcifI0zTk6ZOjv1/qhdKyshPYaRrs9EnRPzp9ywo7TWCnabATi2OTA01ewpnASg12Yl/Vsi4WC6jTNNQpSNLHjwntA1ZqqNMnQV+u8LCZZP1MgKdpwBOLywsjWR7RJ+DTNPDpk6R/3FrOeLlwJgBP04CnT4o+mrssYk0m2NM07Inle7s/Qkw52GMnqNNkicbj/NXOkifJqgN0mly9SH8djUvg+ZmATtNAp0+CvlztkJKtcQI4TQOcuPqGe8tWaBPIaRrkxNXVGz+DxMIjxwRvmoY3fXLzj0YieYfeCeA0DXAyufW4R+J4nvwWIKdpkNMnQ5+vlnv5vWkCOk0DnUx2/R8MT0xI7QRxmoY4fRL0j2Z5fZVEMAGdpoFORuUuArss8jfBnKZhTkGK/v7db7nfeYI8TWlexqBJSb3oE9RpikYzMVF8iwJZE9RpGur06YSMVJHD/xzOBBZrqBO7GOTDxU5BjNUEb5qGN7GraXkEkyz8YhPAaRrg5FshX4XHg8MtaNM0tOnTCLneMa/BRwikaRrSFLRArggt9wKwUAOaPg2Qj2tCyXdJYKZpMBP371LZ217np2OgpmlQ0yeDcp9G17D2wwRnmoYzmZxFXB9HjS9tE4Bp1h6Nx9Vxv+5L0sd1gjDNOiKNu4C1LHLZJxDTNIiJfQDy7pnSKEhlAi5NA5d4uHric+kUnMBL0+AlM427hUXJAOYEYJoGMPFwxL6MNA5qAjFNg5h4uIpiyuufAus0kIl94HFrZ2i7f6CwTAOZeLj7fKPUgzbBmKZhTOwDjiVrMj4BmaaBTDx8HGW5IsHDScA8DWLi4ePB1jsrINNsM1LBO6GWnyHBmKaWSOLOL7oS66KlBsA0DWDi6XNY5lWvKvkxgEzTQCb2jcPKTN14E5xpGs7EvnFY6zEkmoBM00Amnj48XxbdQCZI0zSkiV288V4XM8x6mMBM02Am9vHGoyzvnyBN05Amnl8/8V6Yf5HTPwGapgFNPH2t1xYXJplATNMgJp4+okWPunvxzRGMaRrGxPObV3yUmcto7ARlmp0iDZPune6roEyzcyRxc4i+aPo8AZqmAU2fVHy+iuYnmesTnGkaziTFpbOMeR2VwscBEzWUSco3LP8owrDIw5+gTNNQJiluV1mUu56gTNNQJnFMZQ+KSXoeTjCmaRiTUcAHrPYU7E4gpmkQk5TvpnKU7o36DU7gpWnw0if7/thRxmWh0c8AXJoGLknxCSztx3GLyl4JCNM0hEk8UlmE5k0QpjnESzynr2OhxOYFwDRHjRRMyd3TRMOlAsA0b8DUvv3A92Xfy+qhwkBvwGQ0nrVClGOd",
							"Cbo0b7rUon7gZ4GG9NwDwDRvwNS+LcHp7Ce52u+BmOaNmNq3KzhddLjH2Y0TiGneiOklcbsnrlpmztaBl+aNl1rUDpxlhXUmANO8AdNL5c6RlDQycIIvzZsvtW838KMuEudHWsClecOlZnt437nEI2eYE4BpzhZpmMZuCzw0AZnmVK/y8n5x1sJgAjHNaQy1uWSWprm7GHxpzuEl+PHk9bzm5wRgmnNGGsgl5h6GOW5/dxro8YfX+PcZTHQReroNJqiQV3kOYaNl1rGNZEhwJHFzlR53wt3GCQTkLfBp31pW7tntX6mQqV7m2V3KRVbCn9Ig0SKJu5cLZ0fr7a8VEvqWeKHHq+ZwDx5Gx/gejTd3+vyFDEiMSOLXqwxBuCNsQyc0jHWqu6t0uu4q0TwIFkrFazzV9q7K5/E8CPZJFM3jjiimNJh/GwoDJX5rfMqES5b4v42EiZJ4CZMbSZmzehsJ86QaSWCZDE5jFrahsE9qb43PZYWu9IhwHjBQUq9hari2PD97GwsrpR5NxBamjI9P20hYKY23xDsObObxSttQWCnNSANfL6mpD48Kw0q5eI0nYHLkFeC3obBSNlbqXMMH/x6xI24bCitljjTuRK+yKKu/DYahskQqOIWdFf96PBEYKte3xDsIrGme/rqNhaVy8yKmi0tZnOO2wbBV1mgqd9oKnYeGeCYwVe5vjbcnrF80NNaArfKINMAgz3i0/NfAWnl6FdP/GFXdIksTWKuUt8anUnjaJ2wbCWMV8hIPt+9nIym3QQnsVDiawd0q9Kxrq9nDEBiqGEMdDtofbr845HEbCkuV6jXMBnNWQZTgt8BKpUUCv0zlLklWi8BERd8SbwapfHqhwhcCC5UeSWDl135eFUIJGKgML1Ffufd9cYQSWKjMt8w7aHLU0I1FpcI6a4nGm86tcbXAbSCMs1KkgBNYve5/0bOoMNDKb4l3PUop+eOsMM4qkQRwBNeD64SfjArbrDWSwDKhumq4sI2GhdbHQomcI6xf6RHhI4WFVo0k4C9unLfU3sbCRmv3Is++Uk9PmMZPFUZax1vjXflo9Cy7YRsJA63TS9TnxczcPBpstJVI4tfTNpZn9ksarLTRW+OdP9zqovDyNhiG2tir6KvPcVwufRsJQ20STQTLBbXgQkttsNRW3xpvTl/b9e2I3kuDmbYWadzv5SqCFP4UmGlTL/FOgsyubw1G2oyRsnOFzZJvjg022oaXeFrpzX7dWbJXCzttM5oJlsvks8xO9EgVdqrlLfHp19oWxfW2wbBUJa9i9hY9Aw6iR6IwU+VIAoewWq8Lg9sVFEaq8hZ4F6iYeU+QbSiMVGukgVvL2RPEB29u42Ch2rzA4wbbTyM9vfYobFT1LfJ2hCHkMXyasFHtXqI/ccWLm5PCRnVEEtha5vghRxxJqAEDVWOg4sLA9vtMy25OHRbaS6RxB03q8ozfYaGdIhV8jw83amKhHRba+S3x4Sst7OW5DYOBdonG38j+ao0cTgH22WskAbrSKC9Yto2Fjfb2Fnm3nbg32WihdJho10jjzoUcabOYbShstPdI46aRsqoEt42Gnfbxlnm7wnpf3mg7LLVPr/Jglhk74qkMWOko0XhbMKjHoazbUNjoMDbaXFejUled87bRsNPBXuaJ/pp0RZBlMjDXIZHMTSXbj7PmR2QmA/Y66lvjvWTOQ3J2yR+wV4OePpn2x4eIj4nEB/4BezXoiZqPNKaMjW4jYa6GPH3y7I9G7xpHk23jYKgGOlFz+cNS1w7oAUs11ImCbi19VSODyoTBGvJEzSURI2k1eqgT9jrJSzwlws81Ex/HJmx1cjQL5K11ykM8trGwVMOeaPjcyMVmN2Gohj2Rv+NXueofhY8DdmrYE43v5UXrzBKSt5EwUwOeyAeGnYeP2Ic8YaaGO5G/5p+u7ORDNGGpBjwFrY0Vba9iEdipIU+fxsb1ohwj/i0E+EQGPn16G5drl0nbHGyDCSoUqdxNWsvSa0EAUGQAFA1XAIlqVk1+GymQkEgCJwDhdM0R8BOVGkn8MmX5044t2+AGFWOqvrXxfv48PGPhj1FoqNd4zmV1P8tIrNCh0KNZ3Geys01CfFgmYCgyGIpckNiQZYXPbfSEzPQy8qqvmxT2JgKJIkOizFTu9pm08t8SWBQZFkUzTCmOQwC3gTBVg6I+3Y33pbfvQz26SxFAFBkQFfQ1Lqt8hW0wbNWwKHKhYkd8xOp5wFapRSp35mrbLyEjeTOwVdJI4z43l7MQSWSsYFFkWBS7WLEJn5B/pLBTA6I+yfe712C/vKa1vrbBMFODoj7p9+VqaVGTjypIFBkSxcXnSbbjTtb8LwGGIoOhPon3ckGXpBLcNhQWajAU+zAxGUc8eKgAEzUI6pN5fyho2BxkGwbjNPzpk3Z/ONfO6l7ZMYpAoMgQqE8rYzo9yWE/sG0cTNPAp0/WfbmSehaLBPiJuEcqQJQlS6zeBsI+eUQKv0ycbMssC8ZpyNMn5b4YSJH8FLAnMuzpk3WPVqhBdZttGMzTgCczHrtKq3EC7jYOtmnQE5OrDFbHdS+NvhbgTmS4E5MHkyNLnt1GwkANdmJyZY92mlPzDwbYExn2xOQKHTfNXbcE+EQGPjGFXrHsowP4RAY+MblLy9CrDIJ/KTBPg544aDSRAzACdiKZkQS+W2VZzIUI9Ilq8TLddppatGnZRsNMDYIyKe93mP76sAAKRYZCfZLv65lRfBSfz1RgrQZEfdLvj4PYWSssDMMhkCgyJOqTfn+XY2npRGCthkMFCfhnxlj8lsGhyHCoT/49m9K+kbGCQpGhUJ8M/COoki8HWfZjYLIGRJkE+p8mekUWbxhWa1iUmcwvk4O2slrwKDI86pOKL1dckCYfJOAoauQlnj1maB5aRIBR1DjSuOuG9fxSCBhFBkaZtqg48I9yulHjacBYDYz6dGg9UuI0rWO5DYWtGhjFLmbsyulNLR48igyPCvqztnIchNxnESyKDIv69GY9",
							"fGMSJnBtw2CjBkSxOurSdVXzZxsNIzUg6tOc9XDjjHOHcNMAhSJDoT6NWcu1wyxutaBQZCgUu9J6R3lxiv1RBApFhkKxDxerdZGTvA2GiapEKncc31xkAm+DYaRavYqpsbeqFrENhpkaIvXJJ0YzoSy4iQCkyACpT3dWvkrEBIlc2zBYqaFRn3xiOStLZYH/21BYqsFR7BoaHRU8KLkygEaRoVGffOLDCTxz9wtgFBkY9Ukp5su7NhbeBtAoMjTq05yVrhz8JIlqGwpTNTjqk1l8dA9ffNFBpMgQqU9i8Z6Br5qU6tsGwkYNkGIfKDaTUB4Ci6LeovF3xZ2/4b0BjqKuXuZOcTm6pUp2JQWOIoOjPtnFZa/vwpcLOJsK7NTgqE+O8X4ia2PRnW0bDFM1OOqTY3yUwU0z5IhApMgQKR6uKuUYCwmYqQFSRgK7i8iFw5MfAyBFBkgFWcZaVwSXwKPI8Cj2/mTNEgAIMIoMjOLhAmEU7UW8AIzVgCj2XY3OVOUZP1EYquFQn0RjpGNIvtEBRdHoXuUu8XIgzxEnHW5DYadjRBrY+UdZ2ilgFBkYZVJ8rSO5ZDMBiSJDonj6w1haw2wbCUM1JCrINJ4jv6GCRJEhUSbP9w+G3nDkTwKEIgOhPnnG9ereORdrBSCKDIj6pBtfYTDnAw1/CuzUgCiTJnz3nWhLjkyAUWRglMkWxnoROjsQZyqwVcOj2Lc54rGk/AQkRQZJ8XQbTUn7320jYatzRhJ3YUq+HJ+BBoNIcSmRhm0EdlwcouMUA0jxDaT026FV7o5xvg/YNo4hwF7gKY2k9To+eAGBgEQC+Bkz7imyDasYX9/j34tlyqIA0Da4QaVFKnd58ONzPoJZKMarH2/aTayBOgND8Y2h9OmE+uRQ7i4JXskMyAwvYxLDJAevDArFN4XSb1PW/UDWy0IDFIpvCqVPJ9T+6qIl8beQgaCYKJLATxmovxpqwEaJvcZ4bfoa41IGhWIyVsru6jLLKjaRQaGYaqRyN81LKzttI2Go1LzEkx7GHO8NDPzEpO/x71wXLUuXIQNBMXUvc4cla7+KrsfWASulEU3FFnZLIr0ZDIppviU+qS688lwyMBRz8SpPL7AzZJTijBkGimKmSOTeXPp66YJGMfNb5tMDnM/W6u79gkUxix//9P8eRw/xmc4Chso1msUvk3RT43MQg0YxG0OV0Km8SAdgMClm9TKmtH45fLn+ccBOuUezwOWl90VqF4NHMY+3iO8zWVevFsbKM5LBVnmwpvzVgEmxFK9yX/vbLGloDwNLsdBb4n192a8WIynLuI2FoQpHIncvsHWEIINOsUgkczfRK6tTDPgUS32LfFKQe1b7aRsJc5XmJZ5sfa3r7yL4FItGM7lrweT51Aw+xWJMtvoWenFh620YrFWGH//EXJ40J9m4wadYZqRx75g9uZ8yyBTX8hZ4F3XtugIODDDFlbyKPMfkxQ2EgaW4cqRxl9ttiwMEoBRXeWt8ysCUNI+HwaS41kjiLuqavVXgKK7Nj39SKRu2l/C1Akhx1bfIu2BS0fw8BiDFtUcSeCXHg1qsEwApriOSuWvz8KII1TYYZlqNmboo5aPdnCTOXAaN4la8xhMMs9MZCk0dLIobRZP4ZWoaJklNDBTFjd8S7ziYs3RKujOARnETr/LsLzQvz2MmA0ttNZK505JmWCpzGwZLbe09/n2H2bfcmUezMGgUN41ksGBOJ3v6BQGU4tYjlftURtdnPTJ5gClu463xroLcW46kGVSK2/QaT3zymGHpN2JQKdYSzeGGY7yoYcCAUqzGUoc7ku2PquUwmQGmWNnLPOmVJ/VM1y7AFKtEKrefnK+sRP9IYKda3wLvcjCdky8qaBRr8+MfBLPsobUNhpmqRiq3k0zCCmHbMBio9vf4T/dvClsebMNgnDqi8T9NUE24WgGiWKcf/5y/SjmZXLQ+AKK4l7fE+8qylxDtya4CCMWdvMTDXlTjGjIMAMWdoyncb4GvyAQvAGvsxhrn1w921Mw+aEm0xgGguFev8ayL42KWf8WBobi3SAWNWIUXZaO2wTDLrm8VXyg8SU9lQCju3Us8mcetpZnHDADFfUQS9w0fjbrDrxb4E/f5Fnnf8ZXyuyj4E48SSeCC32R9FwWD4kFexrShqGnxBAZ/4sFviXeq/lnzMv12gj/xEK8yXjWsJI4hZhAoHjWaCMysjrjW7TYOdjoeO6XiNpP9s5RVgGEgKB4aafx8En9WKwYIikf3Kk/0Sy35AQwEisd4S7yuK8f2XBcTgaWOGalgk5erSHho7SBQPIvXkJdXv0W7GvATT3qPf5cWk3ou/OSXgEDxZK/yLBiSxcULFIqnRBq4sUy6quGHGrDSWd8a7+VCM4/WYCAons1rPBVe61iVjWMQKJ4azeROdmnLCwsIFE9jquTcyOOKOctUYK1zRCq4stS5OJCCQPGckcbd77tfUbDxVAQQSkp5y3z650l6MxYgKDEIioL45H5G0wQ/RgChxEAoCugL4mC/q0YAocRAKCIfZknx8VwAocRAqE9hi2O8poW/t6ENGi3SMDnIZ5Jr9kYUMvqWeZfYv8LokufZodG9xhM0RmtnmABDSRnRVH6ZHLMoS12AoMQgKGJP9OnyUybTAIUSQ6FMaYq7wsXMGsBsI2GjhkKRj0reb04LZ6cARIkBUcQunJ/OVPWSysBaDYwiF5qsPXfjCEiUGBJF7CP6Ja9QIUBRYlAUefhyxIum5goeJYZHfcpcHPvVqp/8NhgGa3AUsc+rXMayCICUGCBlykzcH7OS4jkBkBKaXuI5mZ3Ro5nXQgCkhEukcm82fF6HopcDHCUGR30S+OsF9muygwtYlBgW9cneP1oFrSrFb4NhrYZIUfuuHT3OO4m1AkeJwVHUvgBGJ6WB9AIcJQZHUftmiqle7SVCCZiqQVHky77uXKYl3VG3sbBUA6Q+qfu7pR67cjYPmKnBUdTckmmyJC8CHCUGR32S9w+PMp+J",
							"iO7rDBAlBkR9svaP+yGdJ9VkFmBRIuRVnjxkjYPOBRRKhKPhv0whk5YsWRAoMQSK1DmR2zzPZKEE7NPwJ1LfnbWvv+tgUGIYlJkJzmT7deioZJvJwE4NgyL9Rlv2sz9z8kxgpYZBGYmfT8nD5buFoRoSRepKxHBLYZgARIkBUaZFvQ2IqdnBCixKDIsi/aZX1rOjZ/wBAogSA6LIh/OfvqHUpy1gUWJYlGlVfxfizvOpBShKqkQS+I71msfQC1iU1BppYPNnTTNfBDhKDI4yHe8BKVnzQztglBgYRb78q652KNAoMTTKTONOfDkzvcJZwEYNiKLuFsvVTCBduiBRYkgUvau/0hnQt/DrCFiUGBZF3ddUklWVPQGQEgOkKIjo76lLVwCkxAApI/HTLDtKilALcJQYHEXdp8CUHLwKWJQYFkXdpVq2VXPkbTCMtTWvYiqML8pyC3CUNI007m/ZPONyQgkYq2FRQW2YuTiCAEWJQVHku4YNSlNPBSRKDIkiVwF21OtsGX5AQKPE0KhPbRi6UpOyLRMsSgyLovFdMFcSYOB/FFAoMRTqUxjm6u4yk/cBAiWGQH2qwpSrxnEedi7AUGIwFA2XL3Z2JUjXLGCUGBhFwxXrq2ebw3jTBooSg6LIl4HVuvKmCoCUaI9UfpoAtBZ7UwVMSnR4iefeT3mRYQGWEoOlKOAxFxGPJIClxGCpT1GYJ9wqqDwigFJioFRQE4Z0fc4GmxLDpj5VYeT0HQQtE7dRsFJDpj7VYI6dZZ5fjWwSsFLDpsi3DtN+xjdnKrBSw6Y+9WDoaofEyX4LMCUGTNF0O4v0rPv1NhIWasAU+dZhXC+3kH+ksE+DpT7FYOS8kaaXBkAp6TOSuOPFNb+hA0rJKF7i2VE6h5GNAhglBkYxf+sm7V3s96tRvKmBRomhUew8Y4PO2JesqpUAR4nBUZ+c/SOvEz1q/G+BdRoYxd4vxnJxQi8AwzQw6pOszydo1B/5z4BpGhrF7HYUXWzxQFFiUJTJs4dl7VtKj38ITNOAKPZVX0vNzwigUGIo1CdLv55uOc5qhggolBgKxb7sq4ysG902EvY5KZKwJUZzpCYAUTI5UoFj7ywNGFgWIJQYCGUa1N/N5fsyk1LAocRwKBZ3V5GxANkCECUGRJm53GT/dCLH1z9gKDEYisVHipVLI3y5MFIDoVhc7L7unlKOFWClBkCxuN2krt0DQFBiEBSL8x/LVYQ2VqkgUNUQKJavN2yvQXkmhkavpoJBVcOgbpFXo4rFJluBoarBUCy+dWtNHS8VIKoW8RLPqpFlnbIKHFVLjSZy87AjCSDgYRUsqhoWxdXDfVkmM1SwqGpYFNcvqDxiWXQl0yHTvQw9BW05yTGrAFHVgCiubtWc3f40ncaEyoxUfpp+Rj1IMK/gUNVwKK4usLKNM4coMg9wqGo4FNevO+yg0DOJ7a6AUNVAKK7fLabqPFlJrAEzNQTKaCBqrJ0FecMNogJBVYOguLoq/H2kvby3obBTapHGzY45rgZRQZ8qqR//5FDWK/kwMQzQp2roE7dv67ADMCalgirQUzXoiZsva0FnBRf/Q2CbhjuxC0I+CEkSrFUBnaqBTtx8DEzaeXEbCfM00Il9BPLOLRbnyQruVA134uZiKi/8nH42AJ6qAU/su+yVReR/BXmqhjxx8x0r2pl4HD5X2KghT9x8g5e5TA2toE/V0CduIZxMLi0V7KlyjyRu37EmqwXgqfLw4x+/8VlhI/WCV4CnasAT67c23yxtudkCP1WDn1hdmksreQp1BXyqBj596ibJ6V48e/65JwL8VA1+8iWT9hjipHZkBX2qhj59qiaVu89e8E6AnqpBT6wuxFLzUsAV2Kka7MTqcvRF1rs0sFM12CkonNRmnMhdwZyqYU6svm2rXvuBF4B5GtwUFExCh+PwbcA0ZXqJp6tLb3Hp/QrUVGuJxtvPcNKPpQI1VYOaePqMfL6SDf0cYJMGMvH0l/p51ahPXidAUzWgiecXrei2qeX9HSpIUzWkiadLAyNkToaHDbCmaliTL2fR+4z7xlaApmpAE/tayEVWEKECNVWDmj6VLI5ayDUNY6hgTdWwpk8ViyNKZS46JG+DYaMGNX2qWNCD/8MLXAVoqgY08XT3+86rel4VoKk28iqPq7iVMww5U4G9No5UboZXzgig6MECNVWDmqS4BsddsgsCOFM1nEl8RWQp+acDkKkayCTFVxDXH3JE8IUasFQDmcTXQx79apcRasBODWWS4sBKv2rdhysOmKkazCQuCPmo+51gpgrMVA1mkuIhZElDdiooUzWUScq3SYWWde2YCtJUDWmS8r2r7FUrua5kYKaGN5nW9X94+kqtrgpgTlUlUrkdle2gVpkIrFWrFzE9wUt+Ugdvqjdv6rbqyp0fcrVmcAsGrKnerKnbujF31uR1lAynAEO9QVP/Fn55DrTJr4Cd3qCp26orJvPojGLMnids9YZN/Vv8ZX+ePE6nS2TugE31hk0vifsiqUtfFohTvYlTtzVXsGi6xIXEK1BTvVFTt+Vj7iYVkhxfwJrqzZpe4+8jGL6j2c+Afd6wqUdlX0pZxQ1WwKbaW6SCpdJlBVYreFPtGqnAVXnWys9VYKvd2KqvkCx1seeCOtU+Ig1cWA6vzOrhwlj7jGSwXe71TZPojgryVEd5S3wCxPT4CEW/BfCpDvIKTwRybclNEuCpDo5mgC/YXRwknAOMdchb41Mria/twU8CZjqqF3jiKM/chWC1ADrV0aLxd+kKzj/DQE516Fvik5C/cNsAOdXRvcQT3LIHto4kIKyCOtUxomnc/vy8X3wFdarDmKUDLUfyIycxNhXUqc4SaeDmIle9SvdCgJzqpGj8L8Q8l/Mu7MfDKie/x79bHhVddICqIE51SiTy0zSPXLT4qSBOddZIBhV4budVJgMbne0t8/aB1b6qjlZBnepUr/Kkt1TOHixsdPZo/K93WbP0pgDsVOd4y7wjjgutcgUqsFOd",
							"06s8yS1Vr+qIgaU2QKdWSqRhANiKjzRgp1aMwaqLcily+UuD9d8AnVrhSAOL5m/YWwN4akUiGawdPn7RiGdSIVHfEu9KfFrTjmEN3KmV5iVMGGW79oVQQ6Gh0TR+mSxMiTfIBuDUSn9LfM5hefmrBuTUyogkbizJ8ebSAJtamdH4u+0RetBGPwPAqVF5a7zbhKlcaVzR7wBxakRe42l5NOQ8y0XbSwNxasSRBlZLudpiumcB2tTI2GZ313u9HHvxHGCcVCMNkKJZz29H+ChgnNS8xNPwSMtV+sb/Dlgm6VvA1xHT+NLUgJoa9Uji55NMsypF1oCbGo1I5m4coucHPVOBjdJ8q3xyjTk9ijZAp8YlkrjPYLyqE9XAnRqTV3lSWc7SvyNVgZkyv1Xe0fn16svrXi94U2OJxv80eRdJLmwDbmpcIwmY2OGoz1YseFNjY6a+yguNZfXfBt7UWL2MOYzNVU2iBuTUuEcqCA3jdVOHBvLUeLxlPitnHDcW/2ZgqDz9cHna7dQ8Mb+BNzUpkcYdAF7zuOkG3tSE3hrvRmFV0zr5DcSpCXuJd7hLSeh9A3NqItE0cBzb9+AZYa8G6NSkvgXeLFI0t3RApybNSzx1ww+fXWbpIE5NNNLAV4yyqi8NyKmJsc75jcjv2tI22A3QqcnwEk+NfcLRNn4hsE+ZkcgvE25HyckJ5KnV8pZ4VUNSqYueRw3sqVWKRO4qVSV/HqBPrbKXeJIkz9rjwUcU2KlVeY9/H72Kxjy0gTi1Wv144wJreeWKBuDUaos04DE+EwOi3wC7rPoe/yyPw3N1FQj342GWtUfjcebi3SUg6buEYdbhRR4UebYHSb5XQE2tPnb5qfGyG3eZcVmmBszUWvHjnwRibtmJCYSpNYomcJdvrSvC1ECYWuO3ypvS956m3TUQptYkksAraXNxBAVkaq16jSf+q9a0DkEDZGqtvSXeVEWvRk/hL4FxNo0kbkyvcdm0Br7UWo/G3zilrfojNRCm1sZb5V1Df91qsgEytTYjFXtdDC8WIExNix//tPwedEZ8R28EdKmpsVDn95okq3JdDXCpKXsVE/616ljXwJaaSjSV22W07FzVAJea1rfKp6LL1TDKP1OYqCFL5KscE53nxvCZwkQNXCIfXnz6ROLtEHCpGbhE3u8lfeUqauBLzfAlowI3d0EGUPhjYKMGLpGE4fiLcIwGwNQMYCJxlxPlJEWigS21Tl7gKbF3dpwKNiWwpdY5msAv0xw2+4gCLzWDl6h+A7+OIMesW28DW2qGLVF17q7DcZO9EpClZsiS0bABIUm8ZgNWagYrUXXFJ6WvqpM2YKVmsJJReZc+CtYakFIzSInq97DVRp4t0oCTmsFJVF0S5HnpzR0KQErNICWqroUxUVrWooEpNcOUqLrqev2Cl+EWC67UDFciH1NcauJ1A1NqQ/x4kylcc98hqFIbNZK4kx8ldzQBLDUDlqg5f9dIIukaqFIzVOlTt2U3qzPcIf34ASw1A5aMyh3tec0ifBawT8OVPnVb4BFOckkbuFIzXMkUXcEbuTt8Jz8GaKkZtEQupLidGSspfG0gTM0Qpk/1FlRrzdMoGzhTM5yJ2jewpUme3NpAmZqhTNQ8qUdl9HC1gDE1w5g+FVz4Kt6Ws/EGxNRmi1RMdv3SJQnG1KZ6mf7EHMmaYwA1NYOaSB2H3D3JBxHNZGC5BjWRRpUpaWZkBqCpGdBEvitrp6SIvoIyqaFMQSGXUtKERAVhUkOYPoVc+AyyaT8kVmAosFcwbVlnjmQUcEkNXCL9ovqjnEwSpKyAS2rgEqlLjGxtUQBbgZfU4CVfxmWPrFgEpigAkxrA9KniwmdHgRl/FxV8SUuPFO4CbnPZzFDBmLQML/PEgQ06P6/evibGGwPt3+v9kbeyCPdRYCY1mOlTyAXBkz051ikwkxrM9CnkImfXzAWnVoAmNaDpU8ylnp3Z47w3BWlSQ5qo+x7GdXkaUsAmNbCJAryy/Uc0L1yoAE5qgFNUyIWuTStaN2BOapgT9bC+Xg5YFNhJDXb61HIBzWxJTrGCOalhTp9aLuXqmltXzxZGSzOS+WmOJUntEQV0Ui5e4tlqBp1hduGnBMhJDXLi4u79zGtLAXNSw5zYe8jOJs/p6wF5UkOeuLibf78CseMfBJs16IlLWDUsOZQoyJMa8sTFw8met0NXYCc12InfTjK+vmkUnH0VwEkNcOLiCoadSZaL9wJjNcCJiyurfxaUHME0YKWGOHHxCcUI0o8eJ4iTGuLExR/P9lio9BsC5KRCkchPc4aIEgsVvEmFo/F3QyM9oqfj9GoFcFIDnJi+F5pBM63QrUBOapATk0v3OuMhevw8YZ4GObHvNHkmecdfDhAnNcSJyV1oJsXdFhTASQ1wYh9pfPpvR/wrYJkGODH5KpSSl8RW8CY1vInJecearLwXCuSkBjkxuTVSx+kpjH4MgJMa4MT0zY2sQxNAoMBNanAT+2rHZwn6/JfAPqt4lScxEon7mQpMtNZI5S6rx1d6ZLhUwJ7UsCdmhyQ7pdkwCvykBj99qrqgAzElITsKBKUGQbGLMj4K4ks2DRiqAVCfoi6I8U2afiv4kxr+FJR16SPuyqrgT2r406eii1w9hBbF/RQUSg2FYlfoeI9KPDBYpgJTNRSK2d36t5UQxTAoCJQaAsWuv+Rxd0mCbRQASg2ACqq6lH4UbA4VYJ2tRQq3Q7wtFwoQlDaNVPBaakvuLUBQahDUp6jLsZ30HG0qAJQaAMXi9xP5cbaD9pOAbRr2xOLi8MdM+zAq8JMa/MQ+3vh0j6V2BQKlhkB9yrnIGaGXsyMFgFIDoIwI1nuZx502fKLAT2rw06ecy5UgGdYTVoAnNeCJfZBxuwLZo30N7EkNe/qUcalnmVYpufNHwZ/U8KdPHZd6ViZd5bkrGJRq9zKmS8tYNXtQMCjVEU3mrkpV8i8xEJQaBPWp5nLF9sbrDexJDXv6lHGhq2sFR59hoCc16Imr",
							"Wyot6ZGlQE9q0BNXdzU5q2ol6x3sSQ17Yoda9hnOH8nWDPSkBj196reUq5zxwhWtoE9q6BNXd/haE2MFgFIDoLi63WTqCvYqAJQaAPWp48Jn5+PV9RMYSg2GMlVU7qZGvCrooCBR2qdXeVIje8uykhQQSkeJ5vHLpF7EDlcgKDUIil1V4yOhOXO4gkCpIVDcXSbxvpg5PQQCQ6nBUNy/iSzHJnyUtfI/BKZqIBR3B/HlSCwIVjwIlBoCxd2Hu4y0w4QCQqmBUNzdjnKaVvDRAH5Sg5+4u+1EdYVaFARKDYHi7roUn/7NmqrANA2E4v7dV46Mn5XrChBKDYTi7vYVHknGmgI/6SQv8DRfveo1pg5b8CedHMncNUM4TjNVwCc18ImH62JUS54ToGBPatiT0cAlpc4UDSrAkxrwxMOVy690HhiyhwE7NdyJfS3jfn40Yk8NoJMa6MTDF3Hpue8MwEkNcOLhgsPOEND4tgTepIY38XArpunqcN4BnbqBTjz8Mews5hkyow7q1A114vFF+Xs0QFZgvgM7dYOd2IcYl774jnZwp14kErnjw/Q8o8caFRo10vj1qmM5Eo0GDWOp0x3AOq1Ogh3cqRvuxC7U+Gg0vGhC0AGfuoFPZjJYNoy6a5nMgMx4y7yCKvenll87OghUNwQqKO1SONmxO9hTN+zpU9sF9RKzYnYd7Kkb9vSp7FLukOPQL9gBnroBT5/KLsfdBzkXoQaM1bCnT12X/YKvnGd8dYCnbsATB5WN80p0HdCpU/MSJp84L4bQwZw6aTSL+xzWVsUQOphTN8zpU9SFrsbckm92HdipG+z0Ke1yBAToxQTDHwQzNcxJShifPxMQ1wGduoFOn9ouKA2Veyo7sFM32EmKS7xHHHJkI0BO3SAnKQ5OnmUs4w2vAzh1A5yk+DiYugqv7EBO3SAn8aHIRVa3jw7q1A11EodaGpdV04wO7tQNdxIPW3hmnUQ6yFPnHincr+ZyRYefImCnziPSuPOKlx9VsKdu2JOQWzi7W1bzbOsO/NQNfpKAuFCeJ91Bn7qhT+K6TI5rr/FOoQ781A1+kjdwoatk4aIGUAeA6gZACbm8Yr4yAMJ3AwLVDYEScltNn8uvGiBUNxBKyG02qufZO1OBtRoOJa7f5F7O4QBq4auBuRoUJfT1J++pqhkN60BR3aAoIZfnomdng1ABpiozUrj7fs+0hEYHheq1RBL2npk7UTtAVL9B1HhKRzxJk8cxJfvCg0X1m0W9NMDyx3GOiONgOkhUv0nU+JawoOuB5FWmOkhUv0nU+BaywK/h3FSBovqNosa3kgV2rMQh24Gi+o2ijES1TVoWReA7YFS/YdQIiljU64pG8fIFjuo3jhrfGhZ0Vhs/i7m6TxFgVL9h1PgWsdjPZ9JX7WI6kFS/kdSIalhsX4ea5nZ1AKneKBK5q4TPVWmkDiDVG3uVp/jx6Z9ONixQqd6MvVbnCkABG/dQgaR6q378wyoHL25ogFK9tUgDa6YtGXAHlOpN3yqfNi2JU6QDSvXW/fjnZKb7gssnASNtIxK5vQCaB/J0gKne5lvj5QY4CsJQ5GXqwFJdixd4LjNcrpWS/BZwqa4UzePeYCTOouxAUl35Pf5ZKfWCvzNcsABSXcULmE5GJS8y1QGlutZoEjcHbyl96YBSXY15Bp1Y++mLzZ4mzFM1Urkv/yh37J8G7FN7JHC3MOYk1KIDRHUdb4F3E9Z6dYMNnyZMU2ckgfAXFKCOJMCiei9ewqTh9+UpDESqd3qrfLJe2vlOotcKKNU7e4kn42XbYOUwsHCtgkr1LtE87mRK+iHHNTd8IjDRXt8a75wXGUfvG/dagaN6b354f4L25rLXdweP6l0jmRuOaZyK2UGiejfmqX6VnN3P49sGOFTvI9LAKX/2vKZAB4XqfUYauOqf5ZTSXR4kqo/yVnlf9qWfm0n0Y8Ci+qBI4k4Cn2kB1Q4W1QdHEqbJ9yERWihQVB/y1vC0chFP2QGk+qiRDJpOcL8qXcVzgamOFokgqHJ7v2fRP2dkYFJ96FvgXZjypPrpuQlkqo8eqdwesrmKnusgU32MSMVmg5eFCsx1GHP1pZE6x2i+A0n1WaLxP03c/YIZgEv1SZHKr6cG2SoYuoNL9clvmfcRTChlQh1oqk+JJO4ApZXJA031Wb3GE2G5f2R6nrHbgaf6bG+ZV7GXIwR4JIGaHXCqT400cM/fD8+cpCF1wKk+u9cwfb7pbGERPxIY6xxvjReNOYpK9yQJqANP9TkjDbyayQffj6YxwKZGKZGErcGTNFgaQFOjPKZKxceO8fJ7NoCnRuFIBs6x/YyclVYboFOjSKRx88v2N6ZSIVPfMu+Y5PN27D+KA3BqlObHPxeXqWkg2wCZGkWjKfx6joZZbfwBKjVKf0u8OucdNa2iiIUBHDXK8OOfPJfT5ZE6CgeA1CgzmsYdkDyP9xreGQaY1KDy1viEw8wr0SXUgJkSRRp3UuWyR8oAlhrEXuUB/W2BpQaw1CBjpeQ7fdc4eGsASQ2qfvzjFdNliNEAlRrUolncxcJpWTx5gEwN0rfMu8dRlbQ4xQCWGtQjCYQpEaf53QNIatCIJG6clGzaAzhq0HyPf+WFHQ0AFm2WBojU4OJl7tiYs8h8fKEbwFGDKZLA/QXxY9HCB44azG+Jd9O82Y6iu+EkYKEsXuGJs9QW92UbwFCDazQDfL14lUs9QKEGGwNl1wOs0cL9MwChBqsXeQIthbNfAtvkHo3HKuno+xe+Dxgnj7fGOx5GkXDvJwHr5BkJwKVXeFG9agA+DSmRyA1bSp7lMgCfhtBb43XJPwpKhMEFA/BpCHuBZpuxniDNC8AyRaIZ4Oglmh5oB6jTkPqW8JtJFp40wJyGNK8xXp8sTlYpgNMQjSQAWXtbdfwcYE5DjH3K95I/98edlNcYYE5Dhpe44yuP5BZOwnEGqNOQGWmgKKX0/FQ9gJ1GLW+Nd8vikodJDDCnYZgTeb4y5PwpyTMF",
							"dRqGOn2KJdWzzhtTaOVATsMgJxKXMbk/jYUDaIA5DcOcyIXvHy02jocavVwQp2GI06dWUjnruK6sDNBpGOhE4rDkrMeOEs4Ddlq7V3jiLPeIoDyycIA4jToilbtRUz8P5pkKjNVgJ/KEhfOq2gPMaRjm9KmZVK+aSZpHfA1Qp2GoE1UXBXOeBNO3A+o0DHUi34v1rD8Xf4wAnYaBTr5s0lWmMpGAtRru9KmcdNVwSEtRDXCnYbgTVb9w2g9JfVoD2GkY7ES+G+vusNKsfugAexqGPQWlk+pMWf4AeRqGPFF1rrHKcbj2AHUabUbj7wvLTEM+B7jT0BJJwF1ZZFkVY4A7DcOdyAfxj7lcdqBPw9CnT1GLeuaHne798AfBTg2AIhfGf8Rw1IjEDdCnYejTp54Fn8nbLT9KgT8Nw5/Iu8R6W7krB/jTMPyJ+teX3EuSlz+An4bBT59aFsdNoWS5hwP8aRj+FFSyaGMJKgYY1DAMKihlIXVFiwcw1DAYirq7tfRVH68BCjU6RSI2GzwpqTdAoUZnL3EHjO31C1e3a2CoYTAUDXfHLyPNzx+gUMNQKBqOT+6npaOofKgBSzUoilyx8OOjnAUDDHCoYTgUDZd1XPmsdxBOA6ZqUBQNt2Dm+hQCGDUMjKLh4Esry2UHHDUMjqLh3GLljOVLLQ08ahgeRcPtMv+nsHNJsh1GgeiGuiME+rKAN639L6dlW+mLDKhnNYFQXaetz0FJPzQaGQBSQwEpMkX95elM6J8jDxCpoYgUDbs0o+d43h0GtDqyTTG2DghencYAiRqjePGqXkxC4DFAooYiUSSmXKzlteiO0kCsikepNNjMjHQ85QOPGopHkRg7y+f6XXw2BiA1FJAi4yDen7k3HgwEq4AUib05xvFyFUxqKCZF8t3718fNJkgBrSogRfJlL5dn+/1l9XQGGDUUjCIx6KXRiYwN8KiheBSJcRyrtCzq3ZFAsYpHkRjAfy3u4wKSARw1pNosP/zyOJYG60zgqCHNGwnu9TxNVPytFWjUUDSK07fl0V2EdXpzAKSGAlIqjd6htUgjUKriUWyK+u8+GW6jZQGNEkWj2NqK57BkXACjRMEodqr5+VTHJ2BRolgUJ+Ntef1S5P8jGQnynmDvpHetdSW2KxOAKFEgynomXefJB7N2AY4ShaM4WVwpd3MKX6gCICUKSH2sk5IysXafTUeK7qXAh+zxfh5+ioEUw6bovwdDYcWUgEeJ4lFs+rReu9hI5wIcJQpHsQEw45n4u58COlU0isk0B7ue+0kgwFGicJSyLtL3xOOFlQBIiQJSHw+ldbxzuHsiwFKisBTvDOb2le2rZMF7OIBSoqAU23at18FNDai4gEiJIlK8Qxh+LCvcfbcAR4nCUUz2yIyOpgQCJCUKSX18lO4jlX7vNN13DlRKSLwUGlkGzkUCIiWcbApVE1N9ey0BjhKFo7iYfUyNv8igUaJoFBe7jWnHtZQASYlCUmxLkkdfSClKA5EqMsXl+8Lgqlb4cMGmRLEpLsZ1rPChr6WATYliU9b94vIjDvsfCfiUKD5lrS/K44jbw5FAq4pQsXNkVperk/ucIVYFqT7GF+UxtPSdQgWAShSgYsdpfPUq9cYAPiWZvBRvL/ArPnwsYFSS2Sb51V3Wo5uIAFSJAlVc7QHA0U1EwKpEsSqu5k5/LecsUKuiVez4jpeF+l2lgVeJ4lVczVSzqp3dpaqAVomiVWyrlQcuSluNQKiKVXE11fzXW9kisCyAVaJgFdtSZab4uqYAVomCVSrH64JB6zti/hOgKlGoiqspi8ljbWOCRwtWJYpVcTUw8zEc9w/MBbhKSvZyvNSsnjycBbRKSrFZxnYJVvxfBCpVqIqbeWPK0TtdgKpEoSqVBafMWdYw3IcLmSpYxc1s/2s69vsT0CpRtIqb8U7ufGhkJoBVomAV26LlnkPgLYBVomCVGgdemjaW3t1xAFWJQlXc7LHZc3fcnyIAqkSBKm7fldll+hKu3gGqRIEqbmYvcy0fvXYUAkolilJxM1dgWn1MT4MnC04ltXpZtC1vdHtdgKmkNpvjZzWe4QoSDQVaVaCK+9fd8gK3kdWCAFSJAlVswMx9F4w94z4BqRJFqrh/35erhCa6hCIgVaJI1cdeidc9lqCTl4BSiaJUH4el9BQZj3gTA0glClKxrVTOvExSojSQqeJUbNlMb3ELeQGqEoWquJvNfx9+TZuAUomiVB+LpetVuT5Ot82b9yUEoxLFqLjbtpToEWAHAXm27iV455Ye/RPQZhtePM6WnzN/R5pgU6LY1MdY6Xo9Oj8Wit5vADAlCkzxMDNKoufAwAwBTEoUk/qYKt0rwRSDcQGUEgWleJhelBKXPQmIlCgixcN0EbtaRp+2taBSoqgUD7MCK8GtJAGREkWkPpZK17rnuRQaLjbApEQxKWWH9M4kKaQeAiYlikmpgbz7FflP5tjZUgClREGpj6tSWYunqKGZAElJF5vjV27Z0+nLBSAlI3kDeZfGPcQEAh4likcpbwkcjZUc2k8LcJQoHJXJdK6oy2zZyAMsShSLymQrYhYjcD+c4FGieFQ2JcmPg1W43QGPEsWjPv4WdwOA4UMxAYgSBaKyqUi+vZq95nACBCUKQWUy661ro+uWWgrgkyj4ZA0t7vL9GnNOAX0SRZ8y2QYv5XQ7VACgRAGoj6/FYtnh6TEAlAjZFMP49EQDgT6FvYEor/e4MlmAoORFUPLfZM33Sz6eugJCyQuhtixQWO1hT0YBgZKXQKkUv6uVmZ6bBO7PCp2+AGql2O8gS1xvLgBQ8gIoleJ3fMw9qjcXsCd52dM2iJcgL88DNwV0+rKnlWJfcbVy8JLgtADU/YeT5XWB4afm6vPSzTBCPHnx2NWXHFmKz0hGCt5TbMdgt3EwhV5DMzojTfbSYN+Ya1QJMyMLUhQvhe4fNuxea4ZVxCt1mgL+uyqe/HOWGdqQo9kcP56fjw7BM7ojTfeGgh396IdCyxk8",
							"kGXsWfZ7YfVpH+L+O4IM4mV465PK4cvBiaBSSl6Wd6qn8O7gDIVSifYcW6nl5XeU77sN5ukSdEpsE/yWYDlFBQEzEhql7KV4bx8/OxT3YzxjoVIqe5Kt73FDvwr3t4BQqdoUv+LkC6HcxZbu/wKhUvOG8R7mN9erfYZBoaQUaroe3/cm7tfe/T+gTxo2x2/x9fwUEqoLGiXxsrwHeWk5jLlPhSFRTnuSfQ3GdH5vGSplsml+p1/thrXN/qoMkTJ7w3jbVVDEFGYQRMp5T7FfOpbwWsIMgkS52BS/w+I0nqIk+19An1y9eGxVrlM1CRa0VxiStD3JvlFp2b3UOiMgUO5e/DuhpANpmnGQKA+bRdWKnYzNZxwkykqixZa8DPdWF6cMdebkxcPW4vkMt2gUGeLM5GXBpZfUDvNbhkAz7zk+7Y+WsaenrgyB5uylwIN5GrE6a5YMdebixb+mVesdc/8LCDTXPcVuaXFNmyWsZpjRkGhuNs3vfLic5rUMmebuDQX7laeTid03zTgoNI89wV5Qef8WxX/VMuSZxUvxXp+kyGiEU4FCS/JSvA1dclxTOWMh0KIE2r8XXeShD+L/LwUCLWxzvHZi11XTEczyBfos2RsFSl3o6I48oyHTUvY0uzvyY+QVjAQyLdVLoTwrw83fjIVIS/OS4HWpPSzanaEQael7jo8Tf/JNPGccRFqGl+Dt3crrHkT0m0KoRbw0r6t4vc8Iwlm6Qqw17Wm22rDRTt2xZzDUWsnL8k8hAPLm+gqlVrbxvwOwnqMi1xkJqVYlVWvDX2tUtT8jIdNabIpftwriyEd0RkKmtXopcMnlOkophxemQqi17Wn2XkjMB6fIGQyp1m6zqC4vJ2ueGQy91uFleWsqKK6XmbFQa5U9yW7D19vp9W3QakteElzRrxLv0BuE2shLoe6GceBGMUMh1sZ7jk85Zb2vdLsZoNWWvQz/VI368LHCDIVYW7E5fqdhREeJNOi1Kb2a0v3e+NQTbkZDr615abQ5ag1evgaxtu6lePuD98OE1yDVNvYcu6GFAHm544BSm9gcvxOxLIdSBk4dUu3Jy6Lrw4L68hkKrXbac+zGFtfv1cN3pkOsnb0kL22RYOvQIdWebfzvhUlyaDwzgyHWXvYsH1uL9izaPb13KLVXm+LH7RsWAN6z7ZBpb14O7GCuwp1wGJBp/8n045h0y7TGSu9QaR82BWvfx+cWk30mkGgXLwEaHEe1+pwG1DnSnmBfj7XxVNp7/8SAOAd5KfDGP5dsg0/YgDYHezl2oyT/ez4gz5H3FHszyiqRmcOMhDZHsSl+Bq/X2VD2KeAMhThH9YbxdqvIYdP3GQpxjrbn2LtV9AsoZD8DtDm6l0GfuPTDynJAn2N4af5+RuZBPceMhEKHUqgt1H/aTISTk0Cmkrwsr4NlWdNklAZSFbJpfiVhl8xqtDUVSFV4z7E5718NT8IdjECqijwR2ZvH+XjCJ1CrIk/ksMllhBllgV4VfCLru0/9PBYoVvEnImNjWWt4j3KGQrMKQBGZc+TriKX7plwzFIJVCIrouyBbpygHnUC0IjaNuhNWjmkIHIpS8kbz9zuse1wqHLkRWBQpFvWxueBlv+3tpwggihSIIqdwv/+ffyUjTbZpfoX7wusBu/9KQY6y59i2MncL++BAhQCjSMEoshX7bTxVPNE/05Cl2SyqOVI9XC+bwR1Z+p7lc8sl3x+TOM1AmmHTqAKxHkH1GSlIIV6Kv5/FTL4/s94vCxpFikZRMXMOl7vo3s0ApRLZDP3nb5WDSyYzEFol9saA55KS3wdwxkGlCkWRsRS/YTw7+IZAoUhRKDKF+pch5OFcmwCiSIEoqmbnv4psfaEDRJECUVRNa9fEIa8gsChSLIqqXZd116BwhkGYikOpIeCWXqlRPeiMhDAVhKJqXpHrl7iXp96+hQChSEEoqt9uSOXe6PnOVjMU2lQEiqppEp6qf2VhxkGaCkGRMRO/DBKHLWCcURAmZxvet8v5NV6PERAUcfFGgfPkFnMGAoUiRaGofddjd58FOswH4FCkOBQ1448sw8cVBA5FikNRM45816c1By7xMxYKVRiKmqmnHFfJiv+aAUGRQlDUzHwi7VRRQABRpEAUWT/x0dcVAe+5AEORwlDUTOew3A/3lWYwZKpAFDXri9zWSKI0kKuCUdRMAUw9LgoJSIoUkqJmppRnvnd3ZAQkRbnaFL+FGB/PpAlEinLzBvKnfP5OWSBZxaQ+/kn0mHmHyxdQKVJU6mOexM+ZsHepdYZBrgpJUTfb/RYfrhGQFCkkRbYD8qingsIZDbkqKPUxT0LjsHAk0KpiUtTNTeMiT5udaCCQquJS1M17cx32H3aGBC5Fikt9TJRWnWW+a8/MowGVIkWlqBtiKUcXphkNqSouRd28M21EDRJmJHRaupfivT7ZD9CRgKaoDC/Jn2p0XYL1B7AUKSxFw+5clkGflwJIihSSomFmmcfhs/uTBIAUKSD1MU+idS8mB1tTApQiBaXIQpi8Zjt/HBCqolJkEMw144XOWDMWMlVcioZ5Z4K2UjMMKlVQ6mObdN8mKevtd38MSFQRKRp2r9/cy1szDPpULOrjl3StxfguuHAJHwFEkQJRH7uk/Gw17g+6mwLqrOKl+Pc7Y4vtzpjAoaglm2X8avjyccMAFEUKRbGt2K89pI0EEkWKRLE9ILsYxGniB44ihaOYvk5jt5VlYIw+Q6FRhaPY1CI/nTxj8EngUaR4FBs/8f602nKkDhBFCkQ5RhZ9HTy6PyqUqkAU27OxJOuCYPSfQK2KRbEpR67zlc49vKMyo6FYhaOY7C6/LVtN79kARpGCUdbO4jbWCtA4gUVRJy8FXpza4hkKJIo6eylwLnZNPexRCwKKIoWimL+VY7eHKQUEiACiSIEoZnshLN3HFXYIkKeCUMxmk9+ear7wgw4ORYpDMdsrYXyaFUCiSJEoZlNfWSSYFYChSGEoZntdskQepTMS4lQgitk4",
							"WIx+8ihlAo4ihaPYOIuX+5NweOOApEghKWbzqswpJt+zVJQGOlVUitmwypyeacb8rkBSNLKNVxSmr95dNgE0OoqX4N1YrvW+jYdIFYxiW44802U6HFGCR5HiUZy/y7ABu3Z3+QMiRYpIcTYbfqqrzDIaCqSqiBRney7Wo6YsMxJSVURKpcDEks+bWxApUkSKs9nzl+Xr6/4mwFGkcBRnU0CW2+m2CwFIkQJSnL/+r2WU41UTApQiBaU4WyuLuuCnERt4FCkexdncMk4S3UGakdCrVJti/HaV9bx0AI0iaV6at1to9U0sZhzEqlDUxy/pEvxzbTDeVIJGkaJRbAuUJfsV4wQMRQpDfdyS0q+7lLsaYzAoVgyKDXTpxOEujIGgWCEoLtbvhdYOynmyDAzFCkNxsa6vfGhGP4MzsuQ9y77ZT6e2yTO4IEvxsryHZHmtHrx3l0GiWJGoj1FSWuVjgU/aDG3I0fYcu43FVbNdHH0wCBSnbuN/p2OdT3sYBoDiNLwsUFlLpw5RM1qQRonVWiU9N4n8wgcGhGIFoVQO8JdKp+NYBohiBaLY6ehKy+PI/K7gUKw41MckqTx2BcdfBDSKFY36+CThrqtXcMWgUaxoFFeDKVOO4iFRxaGUOdHb8Dj77kYzDvpUEIoteblXR85xJYNAsSJQXM07UvPjEuC+Z6BQrCjUxxopL2ukdpAExElis6i7YQdXEWaAKObkDQVAbKRnuvYEDg7FikN9jCzuiUXcbm4zDMpUGIqHmVHqON08ZNAoVjTq42Wxfo2nDMb7dgFFsUJRPEwnV5FDy9AZDIkqGqWyvJ6VKSqgZYAoViCKh7n3kincjjJYFCsW9TGzuK0mi0+NGRiKFYZiayJecugjNEMhUAWiPj4WtBpaxq3L5vOERBWJ4mH2950OTnMzGCrNZLP8Lol1elbI5gcBheLMXrya7LkEPIyBoFghKBbbXo8iI4wZCYkq/sRiuoY9JxXxZxwMihWDUiNBOfKoi93anwMSVfiJxdRY0gLx7mcQ8IkVfGIx18PQ99D9OSBTBZ9Uinc6kbBwjcGfWPEnFnvdmNeixxsGABQrAMXyLbIsUk+OWTMaGlUASqVR3VvzvVVwhwKdKgLFYrq3yrE974yGVEu2ad7JpQ46dEWawVBrKV6WtzaRTnZ1MxpqVRwq2z6uqYUmoDMUglUQKtsmrpEt4oyDWhWCyk4HV16Fb9H/AsUqCJWTvfuCbgLuM4ZkFYXKaXtxYKgTFDgzKBQrCpWTcXjt62qmmwJqVRAqJ3P9uOWwkJbBoFgxqGxdxEsJrSAYCIoVgsrJdqpIzx3R4KmAQbFiUDlZ872+TnLcfwYqrdXL8TrvpueVcf8ZiLQ2L8Vb/ppc45X/AQ=="
						}), BinaryEncoding.Base64), Compression.Deflate), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"QualityID", type text},{"ProductionID", type text},{"Date", type date},{"LineID", type text},{"MachineID", type text},{"ShiftID", type text},{"ProductID", type text},{"InspectedUnits", Int64.Type},{"ScrapUnits", Int64.Type},{"ReworkUnits", Int64.Type},{"PrimaryDefect", type text}}, "en-US")
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

